Calc:
	scalac ChecksumAccumulator.sc

SingleLineCalc:
	scalac SingleLineCalc.sc

TheseStringsGetsLost:
	scalac TheseStringsGetsLost.sc

AddOperatorAtEndOfLine:
	scalac AddOperatorAtEndOfLine.sc

Singleton:
	scalac Singleton.sc

CompaionObject:
	scalac CompaionObject.sc

all: Calc SingleLineCalc TheseStringsGetsLost AddOperatorAtEndOfLine Singleton CompaionObject

clean:
	rm -rf *.class 
