"use strict";this.default_ContributorServingLoaderClientJs=this.default_ContributorServingLoaderClientJs||{};(function(_){var window=this;
try{
var m,aa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,aa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))},ca=function(a,b){b=ba(a,b);var c;(c=0<=b)&&Array.prototype.splice.call(a,b,1);return c},da=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},fa=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(ea(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var g=0;g<f;g++)a[e+g]=d[g]}else a.push(d)}},
ha=function(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)},ia=function(a){for(var b=[],c=0;c<arguments.length;c++){var d=arguments[c];if(Array.isArray(d))for(var e=0;e<d.length;e+=8192)for(var f=ia.apply(null,ha(d,e,e+8192)),g=0;g<f.length;g++)b.push(f[g]);else b.push(d)}return b},ja=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},ma=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=
0;f<la.length;f++)c=la[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}},oa=function(a){return na(a,function(b){return b},function(b){return new Uint8Array(b)})},qa=function(a,b,c){return"object"===typeof a?pa&&!Array.isArray(a)&&a instanceof Uint8Array?c(a):na(a,b,c):b(a)},na=function(a,b,c){if(Array.isArray(a)){for(var d=Array(a.length),e=0;e<a.length;e++){var f=a[e];null!=f&&(d[e]=qa(f,b,c))}Array.isArray(a)&&a.W&&ra(d);return d}d={};for(e in a)Object.prototype.hasOwnProperty.call(a,
e)&&(f=a[e],null!=f&&(d[e]=qa(f,b,c)));return d},ta=function(a){return na(a,function(b){return"number"===typeof b?isFinite(b)?b:String(b):b},function(b){return sa(b)})},va=function(a){return null==a||a instanceof Uint8Array?a:"string"===typeof a?ua(a):null},xa=function(a,b){a=a||{};b=b||{};var c={},d;for(d in a)Object.prototype.hasOwnProperty.call(a,d)&&(c[d]=0);for(var e in b)Object.prototype.hasOwnProperty.call(b,e)&&(c[e]=0);for(var f in c)if(Object.prototype.hasOwnProperty.call(c,f)&&!wa(a[f],
b[f]))return!1;return!0},wa=function(a,b){if(a==b)return!0;if(pa){var c=a instanceof Uint8Array,d=b instanceof Uint8Array;if(c||d){if(!c)if("string"===typeof a)a=va(a);else return!1;if(!d)if("string"===typeof b)b=va(b);else return!1;if(a.length!==b.length)return!1;for(d=0;d<a.length;d++)if(a[d]!==b[d])return!1;return!0}}if(null==a&&Array.isArray(b)&&b.W&&!b.length||null==b&&Array.isArray(a)&&a.W&&!a.length)return!0;if(!ya(a)||!ya(b))return"number"===typeof a&&isNaN(a)||"number"===typeof b&&isNaN(b)?
String(a)==String(b):!1;if(a.constructor!=b.constructor)return!1;if(a.constructor===Array){c=d=void 0;for(var e=Math.max(a.length,b.length),f=0;f<e;f++){var g=a[f],h=b[f];g&&g.constructor==Object&&(d=g,g=void 0);h&&h.constructor==Object&&(c=h,h=void 0);if(!wa(g,h))return!1}return d||c?(d=d||{},c=c||{},xa(d,c)):!0}if(a.constructor===Object)return xa(a,b);throw Error("n");},Aa=function(a,b){za=b;a=new a(b);za=null;return a},Ba=function(a){return a[n.Symbol.iterator]()},Ca=function(a){var b,c=(a.ownerDocument&&
a.ownerDocument.defaultView||window).document;(b=(c=null===(b=c.querySelector)||void 0===b?void 0:b.call(c,"script[nonce]"))?c.nonce||c.getAttribute("nonce")||"":"")&&a.setAttribute("nonce",b)},Da=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},Ea="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},Fa=function(a){a=["object"==typeof globalThis&&globalThis,
a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("a");},Ga=Fa(this),q=function(a,b){if(b)a:{var c=Ga;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&Ea(c,a,{configurable:!0,writable:!0,value:b})}};
q("Symbol",function(a){if(a)return a;var b=function(f,g){this.g=f;Ea(this,"description",{configurable:!0,writable:!0,value:g})};b.prototype.toString=function(){return this.g};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0,e=function(f){if(this instanceof e)throw new TypeError("b");return new b(c+(f||"")+"_"+d++,f)};return e});
q("Symbol.iterator",function(a){if(a)return a;a=Symbol("c");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=Ga[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&Ea(d.prototype,a,{configurable:!0,writable:!0,value:function(){return Ha(Da(this))}})}return a});
var Ha=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},r=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:Da(a)}},Ia=function(a){if(!(a instanceof Array)){a=r(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a},Ja="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},Ka;
if("function"==typeof Object.setPrototypeOf)Ka=Object.setPrototypeOf;else{var La;a:{var Ma={a:!0},Na={};try{Na.__proto__=Ma;La=Na.a;break a}catch(a){}La=!1}Ka=La?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError("d`"+a);return a}:null}
var Oa=Ka,t=function(a,b){a.prototype=Ja(b.prototype);a.prototype.constructor=a;if(Oa)Oa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.R=b.prototype},Pa=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
q("WeakMap",function(a){function b(){}function c(k){var l=typeof k;return"object"===l&&null!==k||"function"===l}function d(k){if(!Pa(k,f)){var l=new b;Ea(k,f,{value:l})}}function e(k){var l=Object[k];l&&(Object[k]=function(p){if(p instanceof b)return p;Object.isExtensible(p)&&d(p);return l(p)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),p=new a([[k,2],[l,3]]);if(2!=p.get(k)||3!=p.get(l))return!1;p.delete(k);p.set(l,4);return!p.has(k)&&4==p.get(l)}catch(w){return!1}}())return a;
var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var g=0,h=function(k){this.g=(g+=Math.random()+1).toString();if(k){k=r(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}};h.prototype.set=function(k,l){if(!c(k))throw Error("e");d(k);if(!Pa(k,f))throw Error("f`"+k);k[f][this.g]=l;return this};h.prototype.get=function(k){return c(k)&&Pa(k,f)?k[f][this.g]:void 0};h.prototype.has=function(k){return c(k)&&Pa(k,f)&&Pa(k[f],this.g)};h.prototype.delete=function(k){return c(k)&&
Pa(k,f)&&Pa(k[f],this.g)?delete k[f][this.g]:!1};return h});
q("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var h=Object.seal({x:4}),k=new a(r([[h,"s"]]));if("s"!=k.get(h)||1!=k.size||k.get({x:4})||k.set({x:4},"t")!=k||2!=k.size)return!1;var l=k.entries(),p=l.next();if(p.done||p.value[0]!=h||"s"!=p.value[1])return!1;p=l.next();return p.done||4!=p.value[0].x||"t"!=p.value[1]||!l.next().done?!1:!0}catch(w){return!1}}())return a;var b=new WeakMap,c=function(h){this.h={};this.g=f();
this.size=0;if(h){h=r(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}};c.prototype.set=function(h,k){h=0===h?0:h;var l=d(this,h);l.list||(l.list=this.h[l.id]=[]);l.u?l.u.value=k:(l.u={next:this.g,H:this.g.H,head:this.g,key:h,value:k},l.list.push(l.u),this.g.H.next=l.u,this.g.H=l.u,this.size++);return this};c.prototype.delete=function(h){h=d(this,h);return h.u&&h.list?(h.list.splice(h.index,1),h.list.length||delete this.h[h.id],h.u.H.next=h.u.next,h.u.next.H=h.u.H,h.u.head=null,this.size--,
!0):!1};c.prototype.clear=function(){this.h={};this.g=this.g.H=f();this.size=0};c.prototype.has=function(h){return!!d(this,h).u};c.prototype.get=function(h){return(h=d(this,h).u)&&h.value};c.prototype.entries=function(){return e(this,function(h){return[h.key,h.value]})};c.prototype.keys=function(){return e(this,function(h){return h.key})};c.prototype.values=function(){return e(this,function(h){return h.value})};c.prototype.forEach=function(h,k){for(var l=this.entries(),p;!(p=l.next()).done;)p=p.value,
h.call(k,p[1],p[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(h,k){var l=k&&typeof k;"object"==l||"function"==l?b.has(k)?l=b.get(k):(l=""+ ++g,b.set(k,l)):l="p_"+k;var p=h.h[l];if(p&&Pa(h.h,l))for(h=0;h<p.length;h++){var w=p[h];if(k!==k&&w.key!==w.key||k===w.key)return{id:l,list:p,index:h,u:w}}return{id:l,list:p,index:-1,u:void 0}},e=function(h,k){var l=h.g;return Ha(function(){if(l){for(;l.head!=h.g;)l=l.H;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,
value:void 0}})},f=function(){var h={};return h.H=h.next=h.head=h},g=0;return c});var Qa=function(a,b){if(null==a)throw new TypeError("g`"+b);return a+""};q("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var g=d[f];if(b.call(c,g,f,d)){b=g;break a}}b=void 0}return b}});
q("String.prototype.repeat",function(a){return a?a:function(b){var c=Qa(this,"repeat");if(0>b||1342177279<b)throw new RangeError("i");b|=0;for(var d="";b;)if(b&1&&(d+=c),b>>>=1)c+=c;return d}});var Ra=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};q("Array.prototype.keys",function(a){return a?a:function(){return Ra(this,function(b){return b})}});
q("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});var Sa=function(a){return a?a:Array.prototype.fill};q("Int8Array.prototype.fill",Sa);q("Uint8Array.prototype.fill",Sa);q("Uint8ClampedArray.prototype.fill",Sa);q("Int16Array.prototype.fill",Sa);q("Uint16Array.prototype.fill",Sa);q("Int32Array.prototype.fill",Sa);
q("Uint32Array.prototype.fill",Sa);q("Float32Array.prototype.fill",Sa);q("Float64Array.prototype.fill",Sa);var Ta=function(a,b){a=void 0!==a?String(a):" ";return 0<b&&a?a.repeat(Math.ceil(b/a.length)).substring(0,b):""};q("String.prototype.padStart",function(a){return a?a:function(b,c){var d=Qa(this,"padStart");return Ta(c,b-d.length)+d}});q("String.prototype.padEnd",function(a){return a?a:function(b,c){var d=Qa(this,"padStart");return d+Ta(c,b-d.length)}});
q("Promise",function(a){function b(){this.g=null}function c(g){return g instanceof e?g:new e(function(h){h(g)})}if(a)return a;b.prototype.h=function(g){if(null==this.g){this.g=[];var h=this;this.i(function(){h.l()})}this.g.push(g)};var d=Ga.setTimeout;b.prototype.i=function(g){d(g,0)};b.prototype.l=function(){for(;this.g&&this.g.length;){var g=this.g;this.g=[];for(var h=0;h<g.length;++h){var k=g[h];g[h]=null;try{k()}catch(l){this.j(l)}}}this.g=null};b.prototype.j=function(g){this.i(function(){throw g;
})};var e=function(g){this.g=0;this.i=void 0;this.h=[];this.o=!1;var h=this.j();try{g(h.resolve,h.reject)}catch(k){h.reject(k)}};e.prototype.j=function(){function g(l){return function(p){k||(k=!0,l.call(h,p))}}var h=this,k=!1;return{resolve:g(this.C),reject:g(this.l)}};e.prototype.C=function(g){if(g===this)this.l(new TypeError("j"));else if(g instanceof e)this.I(g);else{a:switch(typeof g){case "object":var h=null!=g;break a;case "function":h=!0;break a;default:h=!1}h?this.A(g):this.m(g)}};e.prototype.A=
function(g){var h=void 0;try{h=g.then}catch(k){this.l(k);return}"function"==typeof h?this.J(h,g):this.m(g)};e.prototype.l=function(g){this.s(2,g)};e.prototype.m=function(g){this.s(1,g)};e.prototype.s=function(g,h){if(0!=this.g)throw Error("k`"+g+"`"+h+"`"+this.g);this.g=g;this.i=h;2===this.g&&this.D();this.v()};e.prototype.D=function(){var g=this;d(function(){if(g.B()){var h=Ga.console;"undefined"!==typeof h&&h.error(g.i)}},1)};e.prototype.B=function(){if(this.o)return!1;var g=Ga.CustomEvent,h=Ga.Event,
k=Ga.dispatchEvent;if("undefined"===typeof k)return!0;"function"===typeof g?g=new g("unhandledrejection",{cancelable:!0}):"function"===typeof h?g=new h("unhandledrejection",{cancelable:!0}):(g=Ga.document.createEvent("CustomEvent"),g.initCustomEvent("unhandledrejection",!1,!0,g));g.promise=this;g.reason=this.i;return k(g)};e.prototype.v=function(){if(null!=this.h){for(var g=0;g<this.h.length;++g)f.h(this.h[g]);this.h=null}};var f=new b;e.prototype.I=function(g){var h=this.j();g.T(h.resolve,h.reject)};
e.prototype.J=function(g,h){var k=this.j();try{g.call(h,k.resolve,k.reject)}catch(l){k.reject(l)}};e.prototype.then=function(g,h){function k(B,u){return"function"==typeof B?function(T){try{l(B(T))}catch(R){p(R)}}:u}var l,p,w=new e(function(B,u){l=B;p=u});this.T(k(g,l),k(h,p));return w};e.prototype.catch=function(g){return this.then(void 0,g)};e.prototype.T=function(g,h){function k(){switch(l.g){case 1:g(l.i);break;case 2:h(l.i);break;default:throw Error("l`"+l.g);}}var l=this;null==this.h?f.h(k):
this.h.push(k);this.o=!0};e.resolve=c;e.reject=function(g){return new e(function(h,k){k(g)})};e.race=function(g){return new e(function(h,k){for(var l=r(g),p=l.next();!p.done;p=l.next())c(p.value).T(h,k)})};e.all=function(g){var h=r(g),k=h.next();return k.done?c([]):new e(function(l,p){function w(T){return function(R){B[T]=R;u--;0==u&&l(B)}}var B=[],u=0;do B.push(void 0),u++,c(k.value).T(w(B.length-1),p),k=h.next();while(!k.done)})};return e});
q("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(h){return h};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}});q("Array.prototype.values",function(a){return a?a:function(){return Ra(this,function(b,c){return c})}});
q("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)Pa(b,d)&&c.push(b[d]);return c}});
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var Ua=Ua||{},n=this||self,Va=function(){},ea=function(a){var b=typeof a;b="object"!=b?b:a?Array.isArray(a)?"array":b:"null";return"array"==b||"object"==b&&"number"==typeof a.length},ya=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},Wa=function(a,b,c){return a.call.apply(a.bind,arguments)},Xa=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,
d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}},Ya=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?Ya=Wa:Ya=Xa;return Ya.apply(null,arguments)},Za=function(a,b){a=a.split(".");var c=n;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b},v=function(a,b){function c(){}c.prototype=b.prototype;
a.R=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.wa=function(d,e,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[e].apply(d,g)}},$a=function(a){return a};
v(aa,Error);aa.prototype.name="CustomError";
var ab;
var bb=function(a){for(var b=[],c=0,d=0;d<a.length;d++){var e=a.charCodeAt(d);255<e&&(b[c++]=e&255,e>>=8);b[c++]=e}return b};
var ba=function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},cb=function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1};
var la="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
var db;
var gb=function(a,b){this.i=a===eb&&b||"";this.j=fb};gb.prototype.h=!0;gb.prototype.g=function(){return this.i};var hb=function(a){return a instanceof gb&&a.constructor===gb&&a.j===fb?a.i:"type_error:Const"},fb={},eb={};
var jb=function(a,b){this.i=b===ib?a:""};jb.prototype.h=!0;jb.prototype.g=function(){return this.i.toString()};var ob=function(a,b){a=kb.exec(lb(a).toString());var c=a[3]||"";return mb(a[1]+nb("?",a[2]||"",b)+nb("#",c,void 0))};jb.prototype.toString=function(){return this.i+""};
var lb=function(a){return a instanceof jb&&a.constructor===jb?a.i:"type_error:TrustedResourceUrl"},kb=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/,ib={},mb=function(a){if(void 0===db){var b=null;var c=n.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("ContributorServingLoaderClientJs#html",{createHTML:$a,createScript:$a,createScriptURL:$a})}catch(d){n.console&&n.console.error(d.message)}db=b}else db=b}a=(b=db)?b.createScriptURL(a):a;return new jb(a,ib)},nb=function(a,b,c){if(null==c)return b;if("string"===
typeof c)return c?a+encodeURIComponent(c):"";for(var d in c)if(Object.prototype.hasOwnProperty.call(c,d)){var e=c[d];e=Array.isArray(e)?e:[e];for(var f=0;f<e.length;f++){var g=e[f];null!=g&&(b||(b=a),b+=(b.length>a.length?"&":"")+encodeURIComponent(d)+"="+encodeURIComponent(String(g)))}}return b};
var pb=function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]},qb=function(a,b){return a<b?-1:a>b?1:0};
var x=function(a,b){this.i=b===rb?a:""};x.prototype.h=!0;x.prototype.g=function(){return this.i.toString()};x.prototype.toString=function(){return this.i.toString()};var sb=function(a){return a instanceof x&&a.constructor===x?a.i:"type_error:SafeUrl"},tb=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,rb={};
var y=function(){var a=n.navigator;return a?a.userAgentData||null:null},ub;a:{var vb=n.navigator;if(vb){var wb=vb.userAgent;if(wb){ub=wb;break a}}ub=""}var xb=function(a){var b=y();return b?b.brands.some(function(c){return(c=c.brand)&&-1!=c.indexOf(a)}):!1},z=function(a){return-1!=ub.indexOf(a)};
var yb=function(){return y()?!1:z("Opera")},zb=function(){return y()?xb("Firefox"):z("Firefox")||z("FxiOS")},Ab=function(){return y()?xb("Chromium"):(z("Chrome")||z("CriOS"))&&!(y()?0:z("Edge"))};
var Bb=function(a){Bb[" "](a);return a};Bb[" "]=Va;var Db=function(a){var b=Cb;return Object.prototype.hasOwnProperty.call(b,9)?b[9]:b[9]=a(9)};
var Eb=yb(),Fb=y()?!1:z("Trident")||z("MSIE"),Gb=z("Edge"),Hb=z("Gecko")&&!(-1!=ub.toLowerCase().indexOf("webkit")&&!z("Edge"))&&!(z("Trident")||z("MSIE"))&&!z("Edge"),Ib=-1!=ub.toLowerCase().indexOf("webkit")&&!z("Edge"),Jb;
a:{var Kb="",Lb=function(){var a=ub;if(Hb)return/rv:([^\);]+)(\)|;)/.exec(a);if(Gb)return/Edge\/([\d\.]+)/.exec(a);if(Fb)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Ib)return/WebKit\/(\S+)/.exec(a);if(Eb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Lb&&(Kb=Lb?Lb[1]:"");if(Fb){var Mb,Nb=n.document;Mb=Nb?Nb.documentMode:void 0;if(null!=Mb&&Mb>parseFloat(Kb)){Jb=String(Mb);break a}}Jb=Kb}
var Ob=Jb,Cb={},Pb=function(){return Db(function(){for(var a=0,b=pb(String(Ob)).split("."),c=pb("9").split("."),d=Math.max(b.length,c.length),e=0;0==a&&e<d;e++){var f=b[e]||"",g=c[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];if(0==f[0].length&&0==g[0].length)break;a=qb(0==f[1].length?0:parseInt(f[1],10),0==g[1].length?0:parseInt(g[1],10))||qb(0==f[2].length,0==g[2].length)||qb(f[2],g[2]);f=f[3];g=g[3]}while(0==a)}return 0<=a})};
zb();!z("Android")||Ab()||zb()||yb()||y()&&xb("Silk");Ab();var Qb=(y()?xb("Safari"):z("Safari")&&!(Ab()||(y()?0:z("Coast"))||yb()||(y()?0:z("Edge"))||(y()?xb("Edge"):z("Edg/"))||(y()?xb("Opera"):z("OPR"))||zb()||(y()?xb("Silk"):z("Silk"))||z("Android")))&&!(z("iPhone")&&!z("iPod")&&!z("iPad")||z("iPad")||z("iPod"));
var Rb={},Sb=null,Tb=Hb||Ib||!Qb&&!Fb&&"function"==typeof n.atob,sa=function(a,b){void 0===b&&(b=0);Ub();b=Rb[b];for(var c=Array(Math.floor(a.length/3)),d=b[64]||"",e=0,f=0;e<a.length-2;e+=3){var g=a[e],h=a[e+1],k=a[e+2],l=b[g>>2];g=b[(g&3)<<4|h>>4];h=b[(h&15)<<2|k>>6];k=b[k&63];c[f++]=l+g+h+k}l=0;k=d;switch(a.length-e){case 2:l=a[e+1],k=b[(l&15)<<2]||d;case 1:a=a[e],c[f]=b[a>>2]+b[(a&3)<<4|l>>4]+k+d}return c.join("")},Wb=function(a){if(Tb)return n.atob(a);var b="";Vb(a,function(c){b+=String.fromCharCode(c)});
return b},Xb=function(a){var b=[];Vb(a,function(c){b.push(c)});return b},ua=function(a){var b=a.length,c=3*b/4;c%3?c=Math.floor(c):-1!="=.".indexOf(a[b-1])&&(c=-1!="=.".indexOf(a[b-2])?c-2:c-1);var d=new Uint8Array(c),e=0;Vb(a,function(f){d[e++]=f});return d.subarray(0,e)},Vb=function(a,b){function c(k){for(;d<a.length;){var l=a.charAt(d++),p=Sb[l];if(null!=p)return p;if(!/^[\s\xa0]*$/.test(l))throw Error("m`"+l);}return k}Ub();for(var d=0;;){var e=c(-1),f=c(0),g=c(64),h=c(64);if(64===h&&-1===e)break;
b(e<<2|f>>4);64!=g&&(b(f<<4&240|g>>2),64!=h&&b(g<<6&192|h))}},Ub=function(){if(!Sb){Sb={};for(var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],c=0;5>c;c++){var d=a.concat(b[c].split(""));Rb[c]=d;for(var e=0;e<d.length;e++){var f=d[e];void 0===Sb[f]&&(Sb[f]=e)}}}};
var pa="function"===typeof Uint8Array,Yb={W:{value:!0,configurable:!0}},ra=function(a){Array.isArray(a)&&!Object.isFrozen(a)&&Object.defineProperties(a,Yb);return a},Zb;
var za;
var A=function(a,b,c,d){var e=za;za=null;a||(a=e);e=this.constructor.messageId;a||(a=e?[e]:[]);this.j=e?0:-1;this.g=null;this.h=a;a:{e=this.h.length;a=e-1;if(e&&(e=this.h[a],!(null===e||"object"!=typeof e||Array.isArray(e)||pa&&e instanceof Uint8Array))){this.l=a-this.j;this.i=e;break a}void 0!==b&&-1<b?(this.l=Math.max(b,a+1-this.j),this.i=null):this.l=Number.MAX_VALUE}if(c)for(b=0;b<c.length;b++)a=c[b],a<this.l?(a+=this.j,(e=this.h[a])?ra(e):this.h[a]=$b):(ac(this),(e=this.i[a])?ra(e):this.i[a]=
$b);if(d&&d.length)for(c=0;c<d.length;c++)bc(this,d[c])},$b=Object.freeze(ra([])),ac=function(a){var b=a.l+a.j;a.h[b]||(a.i=a.h[b]={})},C=function(a,b){if(b<a.l){b+=a.j;var c=a.h[b];return c!==$b?c:a.h[b]=ra([])}if(a.i)return c=a.i[b],c!==$b?c:a.i[b]=ra([])},D=function(a,b){return null!=C(a,b)},cc=function(a,b){a=C(a,b);return null==a?a:!!a},E=function(a,b,c){a=C(a,b);return null==a?c:a},dc=function(a,b){var c=void 0===c?!1:c;a=cc(a,b);return null==a?c:a},F=function(a,b,c){b<a.l?a.h[b+a.j]=c:(ac(a),
a.i[b]=c);return a},G=function(a,b,c){return F(a,b,ra(c||[]))},H=function(a,b,c,d){c!==d?F(a,b,c):b<a.l?a.h[b+a.j]=null:(ac(a),delete a.i[b]);return a},bc=function(a,b){for(var c,d,e=0;e<b.length;e++){var f=b[e],g=C(a,f);null!=g&&(c=f,d=g,F(a,f,void 0))}return c?(F(a,c,d),c):0},I=function(a,b,c){a.g||(a.g={});if(!a.g[c]){var d=C(a,c);d&&(a.g[c]=new b(d))}return a.g[c]},ec=function(a,b,c){a.g||(a.g={});if(!a.g[c]){for(var d=C(a,c),e=[],f=0;f<d.length;f++)e[f]=new b(d[f]);a.g[c]=e}return a.g[c]},K=
function(a,b,c){a.g||(a.g={});var d=c?J(c):c;a.g[b]=c;return F(a,b,d)},fc=function(a,b,c,d){a.g||(a.g={});var e=d?J(d):d;a.g[b]=d;(c=bc(a,c))&&c!==b&&void 0!==e&&(a.g&&c in a.g&&(a.g[c]=void 0),F(a,c,void 0));return F(a,b,e)};A.prototype.toJSON=function(){var a=J(this);return Zb?a:ta(a)};
var J=function(a){if(a.g)for(var b in a.g)if(Object.prototype.hasOwnProperty.call(a.g,b)){var c=a.g[b];if(Array.isArray(c))for(var d=0;d<c.length;d++)c[d]&&J(c[d]);else c&&J(c)}return a.h},M=function(a){Zb=!0;try{return JSON.stringify(a.toJSON(),gc)}finally{Zb=!1}},gc=function(a,b){switch(typeof b){case "number":return isFinite(b)?b:String(b);case "object":if(pa&&null!=b&&b instanceof Uint8Array)return sa(b)}return b},N=function(a,b){return Aa(a,b?JSON.parse(b):null)};A.prototype.toString=function(){return J(this).toString()};
var hc=function(a,b){return a==b||!(!a||!b)&&a instanceof b.constructor&&wa(J(a),J(b))};
var ic=function(a){A.call(this,a)};t(ic,A);var jc=function(a){var b=new ic;return H(b,1,a,0)};
var kc={"-":0,Y:2,N:1},lc={},mc=(lc[0]="-",lc[2]="Y",lc[1]="N",lc),nc=function(a){return 4==a.length&&(-1==a.indexOf("-")||"---"===a.substring(1))&&"1"<=a[0]&&"9">=a[0]&&kc.hasOwnProperty(a[1])&&kc.hasOwnProperty(a[2])&&kc.hasOwnProperty(a[3])?!0:!1};
var pc=function(a){A.call(this,a,-1,oc)};t(pc,A);var oc=[3];
var rc=function(a){A.call(this,a,-1,qc)};t(rc,A);var sc=function(a,b){return G(a,1,b)},tc=function(a,b){return G(a,2,b)},uc=function(a,b){return G(a,3,b)},vc=function(a,b){G(a,4,b)},qc=[1,2,3,4];
var wc=function(a){A.call(this,a)};t(wc,A);var xc=function(a){var b=new wc;H(b,1,Math.floor(a.getTime()/1E3),0);H(b,2,1E6*a.getMilliseconds(),0);return b};
var zc=function(a){A.call(this,a,-1,yc)};t(zc,A);zc.prototype.getVersion=function(){return E(this,1,0)};
var Ac=function(a,b){return H(a,1,b,0)},Bc=function(a,b){return K(a,2,b)},Cc=function(a,b){return K(a,3,b)},Dc=function(a,b){return H(a,4,b,0)},Ec=function(a,b){return H(a,5,b,0)},Fc=function(a,b){return H(a,6,b,0)},Gc=function(a,b){return H(a,7,b,"")},Hc=function(a,b){return H(a,8,b,0)},Ic=function(a,b){return H(a,9,b,0)},Jc=function(a,b){return H(a,10,b,!1)},Kc=function(a,b){return H(a,11,b,!1)},Lc=function(a,b){return G(a,12,b)},Mc=function(a,b){return G(a,13,b)},Nc=function(a,b){return G(a,14,
b)},Oc=function(a,b){return H(a,15,b,!1)},Pc=function(a,b){return H(a,16,b,"")},Qc=function(a,b){return G(a,17,b)},Rc=function(a,b){return G(a,18,b)},Sc=function(a,b){a.g||(a.g={});b=b||[];for(var c=ra([]),d=0;d<b.length;d++)c[d]=J(b[d]);a.g[19]=b;return F(a,19,c)},yc=[12,13,14,17,18,19];
var Tc=function(a){A.call(this,a)};t(Tc,A);
var Uc=function(a){a=a.split("~");if(2!==a.length||a[0]!==(1).toString())return null;if(""===a[1])return[];a=a[1].split(".").map(function(b){return Number(b)});return a.some(function(b){return!b})?null:a};
var Vc="a".charCodeAt(),O=ja({ra:0,qa:1,na:2,ia:3,oa:4,ja:5,pa:6,la:7,ma:8,ha:9,ka:10}),Wc=ja({ta:0,ua:1,sa:2});
var Xc=function(a){if(/[^01]/.test(a))throw Error("o`"+a);this.h=a;this.g=0},Yc=function(a){a=P(a,36);var b=new wc;b=H(b,1,Math.floor(a/10),0);return H(b,2,a%10*1E8,0)},Zc=function(a){return String.fromCharCode(Vc+P(a,6))+String.fromCharCode(Vc+P(a,6))},bd=function(a){var b=P(a,16);return!0===!!P(a,1)?(a=$c(a),a.forEach(function(c){if(c>b)throw Error("p`"+c+"`"+b);}),a):ad(a,b)},cd=function(a){for(var b=[],c=P(a,12);c--;){var d=P(a,6),e=P(a,2),f=$c(a),g=b,h=g.push,k=new pc;d=H(k,1,d,0);e=H(d,2,e,
0);f=G(e,3,f);h.call(g,f)}return b},$c=function(a){for(var b=P(a,12),c=[];b--;){var d=!0===!!P(a,1),e=P(a,16);if(d)for(d=P(a,16);e<=d;e++)c.push(e);else c.push(e)}c.sort(function(f,g){return f-g});return c},ad=function(a,b,c){for(var d=[],e=0;e<b;e++)if(P(a,1)){var f=e+1;if(c&&-1===c.indexOf(f))throw Error("q`"+f);d.push(f)}return d},P=function(a,b){if(a.g+b>a.h.length)throw Error("r`"+b);var c=a.h.substring(a.g,a.g+b);a.g+=b;return parseInt(c,2)};
var dd=function(a){if(!a)throw Error("s");a=Math.floor(10*E(a,1,0)+E(a,2,0)/1E8);return Q(a,36)},ed=function(a){if(!a||2!==a.length)throw Error("t`"+a);return Q(a[0].toLowerCase().charCodeAt()-Vc,6)+Q(a[1].toLowerCase().charCodeAt()-Vc,6)},id=function(a){var b=fd(!0)+gd(a),c=a.reduce(function(d,e){return Math.max(d,e)},0);a=fd(!1)+hd(a,c);return Q(c,16)+(b.length<a.length?b:a)},jd=function(a){return Q(a.length,12)+a.map(function(b){return Q(E(b,1,0),6)+Q(E(b,2,0),2)+gd(C(b,3))}).join("")},gd=function(a){var b=
[];a.sort(function(c,d){return c-d});a.forEach(function(c){var d=b[b.length-1];d&&d.end===c-1?d.end=c:b.push({V:c,end:c})});return Q(b.length,12)+b.map(function(c){return c.V===c.end?fd(!1)+Q(c.V,16):fd(!0)+Q(c.V,16)+Q(c.end,16)}).join("")},hd=function(a,b,c){var d=Array(b).fill("0");a.forEach(function(e){if(e>b||c&&-1===c.indexOf(e))throw Error("u`"+e);d[e-1]="1"});return d.join("")},fd=function(a){return!0===a?"1":"0"},Q=function(a,b){if(null==a||null==b)throw Error("v");var c=a.toString(2).padStart(b,
"0");if(c.length>b)throw Error("w`"+a+"`"+b);return c};
var kd=function(a){try{var b=Xb(a).map(function(f){return f.toString(2).padStart(8,"0")}).join(""),c=new Xc(b);if(3!==P(c,3))return null;var d=tc(sc(new rc,ad(c,24,O)),ad(c,24,O)),e=P(c,6);0!==e&&vc(uc(d,ad(c,e)),ad(c,e));return d}catch(f){return null}},ld=function(a){try{var b=0!=C(a,3).length?Math.max.apply(Math,Ia(C(a,3))):0,c=0!=C(a,4).length?Math.max.apply(Math,Ia(C(a,4))):0,d=Math.max(b,c),e=[Q(3,3),hd(C(a,1),24),hd(C(a,2),24),Q(d,6),hd(C(a,3),d),hd(C(a,4),d)].join("").match(/.{1,8}/g).map(function(f){return parseInt(f.padEnd(8,
"0"),2)});return sa(e,4)}catch(f){return null}};
var md=function(a){try{var b=Xb(a).map(function(d){return d.toString(2).padStart(8,"0")}).join(""),c=new Xc(b);return Sc(Rc(Qc(Pc(Oc(Nc(Mc(Lc(Kc(Jc(Ic(Hc(Gc(Fc(Ec(Dc(Cc(Bc(Ac(new zc,P(c,6)),Yc(c)),Yc(c)),P(c,12)),P(c,12)),P(c,6)),Zc(c)),P(c,12)),P(c,6)),!!P(c,1)),!!P(c,1)),ad(c,12,Wc)),ad(c,24,O)),ad(c,24,O)),!!P(c,1)),Zc(c)),bd(c)),bd(c)),cd(c))}catch(d){return null}},nd=function(a){try{var b=[Q(a.getVersion(),6),dd(I(a,wc,2)),dd(I(a,wc,3)),Q(E(a,4,0),12),Q(E(a,5,0),12),Q(E(a,6,0),6),ed(E(a,7,"")),
Q(E(a,8,0),12),Q(E(a,9,0),6),fd(dc(a,10)),fd(dc(a,11)),hd(C(a,12),12,Wc),hd(C(a,13),24,O),hd(C(a,14),24,O),fd(dc(a,15)),ed(E(a,16,"")),id(C(a,17)),id(C(a,18)),jd(ec(a,pc,19))].join("").match(/.{1,8}/g).map(function(c){return parseInt(c.padEnd(8,"0"),2)});return sa(b,4)}catch(c){return null}};
var od=function(a){if(!a||!D(a,1))return null;var b=nd(I(a,zc,1));if(!b)return null;if(D(a,2)){a=ld(I(a,rc,2));if(!a)return null;b=b+"."+a}return b},qd=function(a){if(!a)return null;var b=a.split(".");if(4<b.length)return null;a=md(b[0]);if(!a)return null;var c=new Tc;a=K(c,1,a);b.shift();b=r(b);for(c=b.next();!c.done;c=b.next())switch(c=c.value,pd(c)){case 1:case 2:break;case 3:c=kd(c);if(!c)return null;K(a,2,c);break;default:return null}return a},pd=function(a){try{var b=Xb(a).map(function(c){return c.toString(2).padStart(8,
"0")}).join("");return P(new Xc(b),3)}catch(c){return-1}};
var rd=function(a,b){var c={};if(Array.isArray(b)&&0!==b.length){b=r(b);for(var d=b.next();!d.done;d=b.next())d=d.value,c[d]=-1!==a.indexOf(d)}else for(a=r(a),d=a.next();!d.done;d=a.next())c[d.value]=!0;delete c[0];return c};
var sd=function(a){this.key=a},td=function(a,b){this.key=a;this.defaultValue=void 0===b?!1:b};t(td,sd);
var ud=function(){this.g={}},wd=function(a){var b=vd.g[a.key];if(a instanceof td)return"boolean"===typeof b?b:a.defaultValue;throw Error();};
var xd=function(a){A.call(this,a)};t(xd,A);
var yd=function(a){A.call(this,a)};t(yd,A);var zd=function(a){A.call(this,a)};t(zd,A);
var Ad=function(a){A.call(this,a)};t(Ad,A);var Bd=function(a){A.call(this,a)};t(Bd,A);
var Cd=function(a){A.call(this,a)};t(Cd,A);var Ed=function(a){A.call(this,a,-1,void 0,Dd)};t(Ed,A);var Fd=function(a){A.call(this,a)};t(Fd,A);var Gd=function(a){A.call(this,a)};t(Gd,A);var Dd=[[2,3]];
var Hd=function(a){A.call(this,a)};t(Hd,A);var Id=function(a){A.call(this,a)};t(Id,A);var Jd=function(a){A.call(this,a)};t(Jd,A);var Kd=function(a){A.call(this,a)};t(Kd,A);
var Md=function(a){A.call(this,a,-1,void 0,Ld)};t(Md,A);var Nd=function(a){var b=new Md;return fc(b,11,Ld[0],a)},Ld=[[10,11,8,12,13,14,15,17,19,18,20,21,22]];
var Od=function(a){A.call(this,a)};t(Od,A);
var Pd=function(){this.m=this.m;this.s=this.s};Pd.prototype.m=!1;Pd.prototype.l=function(){if(this.s)for(;this.s.length;)this.s.shift()()};
var Qd=function(a,b){this.type=a;this.g=this.target=b;this.defaultPrevented=!1};Qd.prototype.h=function(){this.defaultPrevented=!0};
var Sd=function(){if(!n.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{n.addEventListener("test",Va,b),n.removeEventListener("test",Va,b)}catch(c){}return a}();
var Ud=function(a,b){Qd.call(this,a?a.type:"");this.relatedTarget=this.g=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.i=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.g=b;if(b=a.relatedTarget){if(Hb){a:{try{Bb(b.nodeName);var e=!0;break a}catch(f){}e=
!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=
a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:Td[a.pointerType]||"";this.state=a.state;this.i=a;a.defaultPrevented&&Ud.R.h.call(this)}};v(Ud,Qd);var Td={2:"touch",3:"pen",4:"mouse"};Ud.prototype.h=function(){Ud.R.h.call(this);var a=this.i;a.preventDefault?a.preventDefault():a.returnValue=!1};
var Vd="closure_listenable_"+(1E6*Math.random()|0);
var Wd=0;
var Xd=function(a,b,c,d,e){this.listener=a;this.g=null;this.src=b;this.type=c;this.capture=!!d;this.U=e;this.key=++Wd;this.P=this.S=!1},Yd=function(a){a.P=!0;a.listener=null;a.g=null;a.src=null;a.U=null};
var Zd=function(a){this.src=a;this.g={};this.h=0};Zd.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.g[f];a||(a=this.g[f]=[],this.h++);var g=$d(a,b,d,e);-1<g?(b=a[g],c||(b.S=!1)):(b=new Xd(b,this.src,f,!!d,e),b.S=c,a.push(b));return b};var ae=function(a,b){var c=b.type;c in a.g&&ca(a.g[c],b)&&(Yd(b),0==a.g[c].length&&(delete a.g[c],a.h--))},$d=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.P&&f.listener==b&&f.capture==!!c&&f.U==d)return e}return-1};
var be="closure_lm_"+(1E6*Math.random()|0),ce={},de=0,fe=function(a,b,c,d,e){if(d&&d.once)ee(a,b,c,d,e);else if(Array.isArray(b))for(var f=0;f<b.length;f++)fe(a,b[f],c,d,e);else c=ge(c),a&&a[Vd]?a.h.add(String(b),c,!1,ya(d)?!!d.capture:!!d,e):he(a,b,c,!1,d,e)},he=function(a,b,c,d,e,f){if(!b)throw Error("x");var g=ya(e)?!!e.capture:!!e,h=ie(a);h||(a[be]=h=new Zd(a));c=h.add(b,c,d,g,f);if(!c.g){d=je();c.g=d;d.src=a;d.listener=c;if(a.addEventListener)Sd||(e=g),void 0===e&&(e=!1),a.addEventListener(b.toString(),
d,e);else if(a.attachEvent)a.attachEvent(ke(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("y");de++}},je=function(){var a=le,b=function(c){return a.call(b.src,b.listener,c)};return b},ee=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)ee(a,b[f],c,d,e);else c=ge(c),a&&a[Vd]?a.h.add(String(b),c,!0,ya(d)?!!d.capture:!!d,e):he(a,b,c,!0,d,e)},me=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)me(a,b[f],c,d,e);else(d=ya(d)?
!!d.capture:!!d,c=ge(c),a&&a[Vd])?(a=a.h,b=String(b).toString(),b in a.g&&(f=a.g[b],c=$d(f,c,d,e),-1<c&&(Yd(f[c]),Array.prototype.splice.call(f,c,1),0==f.length&&(delete a.g[b],a.h--)))):a&&(a=ie(a))&&(b=a.g[b.toString()],a=-1,b&&(a=$d(b,c,d,e)),(c=-1<a?b[a]:null)&&ne(c))},ne=function(a){if("number"!==typeof a&&a&&!a.P){var b=a.src;if(b&&b[Vd])ae(b.h,a);else{var c=a.type,d=a.g;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(ke(c),d):b.addListener&&b.removeListener&&
b.removeListener(d);de--;(c=ie(b))?(ae(c,a),0==c.h&&(c.src=null,b[be]=null)):Yd(a)}}},ke=function(a){return a in ce?ce[a]:ce[a]="on"+a},le=function(a,b){if(a.P)a=!0;else{b=new Ud(b,this);var c=a.listener,d=a.U||a.src;a.S&&ne(a);a=c.call(d,b)}return a},ie=function(a){a=a[be];return a instanceof Zd?a:null},oe="__closure_events_fn_"+(1E9*Math.random()>>>0),ge=function(a){if("function"===typeof a)return a;a[oe]||(a[oe]=function(b){return a.handleEvent(b)});return a[oe]};
var pe=function(){Pd.call(this);this.h=new Zd(this);this.ca=this;this.J=null};v(pe,Pd);pe.prototype[Vd]=!0;pe.prototype.addEventListener=function(a,b,c,d){fe(this,a,b,c,d)};pe.prototype.removeEventListener=function(a,b,c,d){me(this,a,b,c,d)};
var re=function(a,b){var c,d=a.J;if(d)for(c=[];d;d=d.J)c.push(d);a=a.ca;d=b.type||b;if("string"===typeof b)b=new Qd(b,a);else if(b instanceof Qd)b.target=b.target||a;else{var e=b;b=new Qd(d,a);ma(b,e)}e=!0;if(c)for(var f=c.length-1;0<=f;f--){var g=b.g=c[f];e=qe(g,d,!0,b)&&e}g=b.g=a;e=qe(g,d,!0,b)&&e;e=qe(g,d,!1,b)&&e;if(c)for(f=0;f<c.length;f++)g=b.g=c[f],e=qe(g,d,!1,b)&&e};
pe.prototype.l=function(){pe.R.l.call(this);if(this.h){var a=this.h,b=0,c;for(c in a.g){for(var d=a.g[c],e=0;e<d.length;e++)++b,Yd(d[e]);delete a.g[c];a.h--}}this.J=null};var qe=function(a,b,c,d){b=a.h.g[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.P&&g.capture==c){var h=g.listener,k=g.U||g.src;g.S&&ae(a.h,g);e=!1!==h.call(k,d)&&e}}return e&&!d.defaultPrevented};
var se=function(){};se.prototype.g=null;var ue=function(a){var b;(b=a.g)||(b={},te(a)&&(b[0]=!0,b[1]=!0),b=a.g=b);return b};
var ve,we=function(){};v(we,se);var xe=function(a){return(a=te(a))?new ActiveXObject(a):new XMLHttpRequest},te=function(a){if(!a.h&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.h=d}catch(e){}}throw Error("z");}return a.h};ve=new we;
var ye=function(a,b){this.h=Ba(a);this.i=b;this.j=0};ye.prototype[Symbol.iterator]=function(){return this};ye.prototype.next=function(){var a=this.h.next();return{value:a.done?void 0:this.i.call(void 0,a.value,this.j++),done:a.done}};var ze=function(a,b){return new ye(a,b)},Ae=function(a){this.i=a;this.h=0};Ae.prototype[Symbol.iterator]=function(){return this};Ae.prototype.next=function(){for(;this.h<this.i.length;){var a=this.i[this.h].next();if(!a.done)return a;this.h++}return{done:!0}};
var Be=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c]=arguments[c];return new Ae(b.map(Ba))};
var Ce="StopIteration"in n?n.StopIteration:{message:"StopIteration",stack:""},De=function(){};De.prototype.next=function(){return De.prototype.g.call(this)};De.prototype.g=function(){throw Ce;};De.prototype.M=function(){return this};
var Ie=function(a){if(a instanceof Ee||a instanceof Fe||a instanceof Ge)return a;if("function"==typeof a.next)return new Ee(function(){return He(a)});if("function"==typeof a[Symbol.iterator])return new Ee(function(){return a[Symbol.iterator]()});if("function"==typeof a.M)return new Ee(function(){return He(a.M())});throw Error("A");},He=function(a){if(!(a instanceof De))return a;var b=!1;return{next:function(){for(var c;!b;)try{c=a.g();break}catch(d){if(d!==Ce)throw d;b=!0}return{value:c,done:b}}}},
Ee=function(a){this.h=a};Ee.prototype.M=function(){return new Fe(this.h())};Ee.prototype[Symbol.iterator]=function(){return new Ge(this.h())};Ee.prototype.i=function(){return new Ge(this.h())};var Fe=function(a){this.h=a};t(Fe,De);Fe.prototype.g=function(){var a=this.h.next();if(a.done)throw Ce;return a.value};Fe.prototype.next=function(){return Fe.prototype.g.call(this)};Fe.prototype[Symbol.iterator]=function(){return new Ge(this.h)};Fe.prototype.i=function(){return new Ge(this.h)};
var Ge=function(a){Ee.call(this,function(){return a});this.j=a};t(Ge,Ee);Ge.prototype.next=function(){return this.j.next()};
var S=function(a,b){this.h={};this.g=[];this.i=this.size=0;var c=arguments.length;if(1<c){if(c%2)throw Error("B");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof S)for(c=a.G(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])};S.prototype.F=function(){Je(this);for(var a=[],b=0;b<this.g.length;b++)a.push(this.h[this.g[b]]);return a};S.prototype.G=function(){Je(this);return this.g.concat()};
S.prototype.has=function(a){return Ke(this.h,a)};S.prototype.isEmpty=function(){return 0==this.size};var Je=function(a){if(a.size!=a.g.length){for(var b=0,c=0;b<a.g.length;){var d=a.g[b];Ke(a.h,d)&&(a.g[c++]=d);b++}a.g.length=c}if(a.size!=a.g.length){var e={};for(c=b=0;b<a.g.length;)d=a.g[b],Ke(e,d)||(a.g[c++]=d,e[d]=1),b++;a.g.length=c}};m=S.prototype;m.get=function(a,b){return Ke(this.h,a)?this.h[a]:b};m.set=function(a,b){Ke(this.h,a)||(this.size+=1,this.g.push(a),this.i++);this.h[a]=b};
m.forEach=function(a,b){for(var c=this.G(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};m.keys=function(){return Ie(this.M(!0)).i()};m.values=function(){return Ie(this.M(!1)).i()};m.entries=function(){var a=this;return ze(this.keys(),function(b){return[b,a.get(b)]})};m.M=function(a){Je(this);var b=0,c=this.i,d=this,e=new De;e.g=function(){if(c!=d.i)throw Error("C");if(b>=d.g.length)throw Ce;var f=d.g[b++];return a?f:d.h[f]};e.next=e.g.bind(e);return e};
var Ke=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
var Le=function(a){if(a.F&&"function"==typeof a.F)return a.F();if("undefined"!==typeof Map&&a instanceof Map||"undefined"!==typeof Set&&a instanceof Set)return Array.from(a.values());if("string"===typeof a)return a.split("");if(ea(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return ja(a)},Me=function(a){if(a.G&&"function"==typeof a.G)return a.G();if(!a.F||"function"!=typeof a.F){if("undefined"!==typeof Map&&a instanceof Map)return Array.from(a.keys());if(!("undefined"!==typeof Set&&
a instanceof Set)){if(ea(a)||"string"===typeof a){var b=[];a=a.length;for(var c=0;c<a;c++)b.push(c);return b}b=[];c=0;for(var d in a)b[c++]=d;return b}}},Ne=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);else if(ea(a)||"string"===typeof a)Array.prototype.forEach.call(a,b,void 0);else for(var c=Me(a),d=Le(a),e=d.length,f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)};
var Oe=function(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)},Pe=function(a){this.g=a||n.document||document};
var Qe=function(a,b,c){if("function"===typeof a)c&&(a=Ya(a,c));else if(a&&"function"==typeof a.handleEvent)a=Ya(a.handleEvent,a);else throw Error("E");return 2147483647<Number(b)?-1:n.setTimeout(a,b||0)};
var Re=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^\\/?#]*)@)?([^\\/?#]*?)(?::([0-9]+))?(?=[\\/?#]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,Se=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};
var Te=function(a){pe.call(this);this.headers=new S;this.A=a||null;this.i=!1;this.B=this.g=null;this.I="";this.j=this.D=this.o=this.C=!1;this.K=0;this.v=null;this.X="";this.L=this.$=!1};v(Te,pe);var Ue=/^https?$/i,Ve=["POST","PUT"],We=[];Te.prototype.da=function(){this.m||(this.m=!0,this.l());ca(We,this)};
var $e=function(a,b,c){var d={"Content-Type":"text/plain"};if(a.g)throw Error("F`"+a.I+"`"+b);a.I=b;a.C=!1;a.i=!0;a.g=a.A?xe(a.A):xe(ve);a.B=a.A?ue(a.A):ue(ve);a.g.onreadystatechange=Ya(a.O,a);try{a.D=!0,a.g.open("POST",String(b),!0),a.D=!1}catch(f){Xe(a);return}b=c||"";var e=new S(a.headers);d&&Ne(d,function(f,g){e.set(g,f)});d=e.G().find(function(f){return"content-type"==f.toLowerCase()});c=n.FormData&&b instanceof n.FormData;!(0<=ba(Ve,"POST"))||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");
e.forEach(function(f,g){this.g.setRequestHeader(g,f)},a);a.X&&(a.g.responseType=a.X);"withCredentials"in a.g&&a.g.withCredentials!==a.$&&(a.g.withCredentials=a.$);try{Ye(a),0<a.K&&(a.L=Ze(a.g),a.L?(a.g.timeout=a.K,a.g.ontimeout=Ya(a.Z,a)):a.v=Qe(a.Z,a.K,a)),a.o=!0,a.g.send(b),a.o=!1}catch(f){Xe(a)}},Ze=function(a){return Fb&&Pb()&&"number"===typeof a.timeout&&void 0!==a.ontimeout};Te.prototype.Z=function(){"undefined"!=typeof Ua&&this.g&&(re(this,"timeout"),this.abort(8))};
var Xe=function(a){a.i=!1;a.g&&(a.j=!0,a.g.abort(),a.j=!1);af(a);bf(a)},af=function(a){a.C||(a.C=!0,re(a,"complete"),re(a,"error"))};Te.prototype.abort=function(){this.g&&this.i&&(this.i=!1,this.j=!0,this.g.abort(),this.j=!1,re(this,"complete"),re(this,"abort"),bf(this))};Te.prototype.l=function(){this.g&&(this.i&&(this.i=!1,this.j=!0,this.g.abort(),this.j=!1),bf(this,!0));Te.R.l.call(this)};Te.prototype.O=function(){this.m||(this.D||this.o||this.j?cf(this):this.ea())};Te.prototype.ea=function(){cf(this)};
var cf=function(a){if(a.i&&"undefined"!=typeof Ua&&(!a.B[1]||4!=(a.g?a.g.readyState:0)||2!=df(a)))if(a.o&&4==(a.g?a.g.readyState:0))Qe(a.O,0,a);else if(re(a,"readystatechange"),4==(a.g?a.g.readyState:0)){a.i=!1;try{var b=df(a);a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=String(a.I).match(Re)[1]||null;if(!f&&n.self&&n.self.location){var g=n.self.location.protocol;f=g.substr(0,g.length-1)}e=!Ue.test(f?
f.toLowerCase():"")}d=e}d?(re(a,"complete"),re(a,"success")):af(a)}finally{bf(a)}}},bf=function(a,b){if(a.g){Ye(a);var c=a.g,d=a.B[0]?Va:null;a.g=null;a.B=null;b||re(a,"ready");try{c.onreadystatechange=d}catch(e){}}},Ye=function(a){a.g&&a.L&&(a.g.ontimeout=null);a.v&&(n.clearTimeout(a.v),a.v=null)},df=function(a){try{return 2<(a.g?a.g.readyState:0)?a.g.status:-1}catch(b){return-1}};
var ef=function(a,b){b=void 0===b?{}:b;this.g=a?new x(lb(ob(mb(C(a,4)||""),b)).toString(),rb):null},ff=function(a,b){if(a.g){F(b,9,Date.now());a=sb(a.g);b=M(b);var c=new Te;We.push(c);c.h.add("ready",c.da,!0,void 0,void 0);$e(c,a,b)}};
var gf=function(a){A.call(this,a)};t(gf,A);
var hf=function(a){A.call(this,a)};t(hf,A);var jf=function(a){A.call(this,a)};t(jf,A);
var kf=function(a){A.call(this,a)};t(kf,A);var lf=function(a){A.call(this,a)};t(lf,A);var mf=function(a){A.call(this,a)};t(mf,A);var nf=function(a){A.call(this,a)};t(nf,A);var of=function(a){A.call(this,a)};t(of,A);
var pf=function(a){A.call(this,a)};t(pf,A);var qf=function(a){A.call(this,a)};t(qf,A);
var rf=function(a){this.g=a||{cookie:""}};m=rf.prototype;
m.set=function(a,b,c){var d=!1;if("object"===typeof c){var e=c.xa;d=c.ya||!1;var f=c.domain||void 0;var g=c.path||void 0;var h=c.aa}if(/[;=\s]/.test(a))throw Error("G`"+a);if(/[;\r\n]/.test(b))throw Error("H`"+b);void 0===h&&(h=-1);this.g.cookie=a+"="+b+(f?";domain="+f:"")+(g?";path="+g:"")+(0>h?"":0==h?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(Date.now()+1E3*h)).toUTCString())+(d?";secure":"")+(null!=e?";samesite="+e:"")};
m.get=function(a,b){for(var c=a+"=",d=(this.g.cookie||"").split(";"),e=0,f;e<d.length;e++){f=pb(d[e]);if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};m.G=function(){return sf(this).keys};m.F=function(){return sf(this).values};m.isEmpty=function(){return!this.g.cookie};
var sf=function(a){a=(a.g.cookie||"").split(";");for(var b=[],c=[],d,e,f=0;f<a.length;f++)e=pb(a[f]),d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
var tf=function(a,b,c){a=new rf(a);a.get(b);a.set(b,"",{aa:0,path:"/",domain:c})};
var uf=new td("45356989"),vf=new td("45354111");
var wf=function(){this.g={};var a=n.__fcexpdef||"";try{var b=JSON.parse(a)[0];a="";for(var c=0;c<b.length;c++)a+=String.fromCharCode(b.charCodeAt(c)^"\u0003\u0007\u0003\u0007\b\u0004\u0004\u0006\u0005\u0003".charCodeAt(c%10));this.g=JSON.parse(a)}catch(d){}},xf;t(wf,ud);var yf=function(){xf||(xf=new wf);return xf};
var vd=yf(),Af=function(a){a=zf(a,"FCCDCF");try{return a?N(kf,a):null}catch(b){return null}},Bf=function(a){a=zf(a,"FCNEC");try{return a?N(pf,a):null}catch(b){return null}},Cf=function(a){return(a=(new rf(a)).get("DATA_USE_CONSENT",""))?a:null},Df=function(a){return(a=Af(a))?I(a,nf,4):null},zf=function(a,b){return(a=(new rf(a)).get(b,""))?a:null},Ef=function(a){var b=Af(a);if(!b)return Cf(a);b=I(b,mf,3);if(!b||!D(b,1))return Cf(a);a=C(b,2);var c=Date.now();if(a){if(c<a||c>a+33696E6)return null}else return null;
return C(b,1)},Ff=function(a){return(a=Af(a))?I(a,of,5)||null:null},Gf=function(a,b,c,d){var e=new Bd;e=F(e,3,a);e=F(e,2,b);if(a||b)!a&&b?F(e,5,5):a&&!b?F(e,5,2):a&&b&&(c?(a=F(e,4,1),F(a,5,3)):(a=F(e,4,2),F(a,5,4))),a=new Ad,e=K(a,1,e),a=new Md,e=fc(a,22,Ld[0],e),ff(d,e)};
var If=function(a){A.call(this,a,-1,Hf)};t(If,A);var Hf=[1,2,3,4];
var Jf=function(a,b,c){this.g=a;this.h=b;this.i=c;yf()};
var Kf=function(a,b){this.h=a|0;this.g=b|0},Lf=function(a){return 4294967296*a.g+(a.h>>>0)};Kf.prototype.toString=function(a){a=a||10;if(2>a||36<a)throw Error("I`"+a);var b=this.g>>21;if(0==b||-1==b&&(0!=this.h||-2097152!=this.g))return b=Lf(this),10==a?""+b:b.toString(a);b=14-(a>>2);var c=Math.pow(a,b),d=U(c,c/4294967296);c=Mf(this,d);d=Math.abs(Lf(this.add(V(Nf(c,d)))));var e=10==a?""+d:d.toString(a);e.length<b&&(e="0000000000000".substr(e.length-b)+e);d=Lf(c);return(10==a?d:d.toString(a))+e};
var Of=function(a){return 0==a.h&&0==a.g},Pf=function(a,b){return a.h==b.h&&a.g==b.g},Qf=function(a,b){return a.g==b.g?a.h==b.h?0:a.h>>>0>b.h>>>0?1:-1:a.g>b.g?1:-1},V=function(a){var b=~a.h+1|0;return U(b,~a.g+!b|0)};Kf.prototype.add=function(a){var b=this.g>>>16,c=this.g&65535,d=this.h>>>16,e=a.g>>>16,f=a.g&65535,g=a.h>>>16;a=(this.h&65535)+(a.h&65535);g=(a>>>16)+(d+g);d=g>>>16;d+=c+f;b=(d>>>16)+(b+e)&65535;return U((g&65535)<<16|a&65535,b<<16|d&65535)};
var Nf=function(a,b){if(Of(a))return a;if(Of(b))return b;var c=a.g>>>16,d=a.g&65535,e=a.h>>>16;a=a.h&65535;var f=b.g>>>16,g=b.g&65535,h=b.h>>>16;b=b.h&65535;var k=a*b;var l=(k>>>16)+e*b;var p=l>>>16;l=(l&65535)+a*h;p+=l>>>16;p+=d*b;var w=p>>>16;p=(p&65535)+e*h;w+=p>>>16;p=(p&65535)+a*g;w=w+(p>>>16)+(c*b+d*h+e*g+a*f)&65535;return U((l&65535)<<16|k&65535,w<<16|p&65535)},Mf=function(a,b){if(Of(b))throw Error("J");if(0>a.g){if(Pf(a,Rf)){if(Pf(b,Sf)||Pf(b,Tf))return Rf;if(Pf(b,Rf))return Sf;var c=1;if(0==
c)c=a;else{var d=a.g;c=32>c?U(a.h>>>c|d<<32-c,d>>c):U(d>>c-32,0<=d?0:-1)}c=Mf(c,b);d=1;if(0!=d){var e=c.h;c=32>d?U(e<<d,c.g<<d|e>>>32-d):U(0,e<<d-32)}if(Pf(c,Uf))return 0>b.g?Sf:Tf;a=a.add(V(Nf(b,c)));return c.add(Mf(a,b))}return 0>b.g?Mf(V(a),V(b)):V(Mf(V(a),b))}if(Of(a))return Uf;if(0>b.g)return Pf(b,Rf)?Uf:V(Mf(a,V(b)));for(d=Uf;0<=Qf(a,b);){c=Math.max(1,Math.floor(Lf(a)/Lf(b)));e=Math.ceil(Math.log(c)/Math.LN2);e=48>=e?1:Math.pow(2,e-48);for(var f=Vf(c),g=Nf(f,b);0>g.g||0<Qf(g,a);)c-=e,f=Vf(c),
g=Nf(f,b);Of(f)&&(f=Sf);d=d.add(f);a=a.add(V(g))}return d};Kf.prototype.and=function(a){return U(this.h&a.h,this.g&a.g)};Kf.prototype.or=function(a){return U(this.h|a.h,this.g|a.g)};Kf.prototype.xor=function(a){return U(this.h^a.h,this.g^a.g)};var Vf=function(a){return 0<a?0x7fffffffffffffff<=a?Wf:new Kf(a,a/4294967296):0>a?-0x7fffffffffffffff>=a?Rf:V(new Kf(-a,-a/4294967296)):Uf},U=function(a,b){return new Kf(a,b)},Uf=U(0,0),Sf=U(1,0),Tf=U(-1,-1),Wf=U(4294967295,2147483647),Rf=U(0,2147483648);
/*

 Copyright 2005, 2007 Bob Ippolito. All Rights Reserved.
 Copyright The Closure Library Authors.
 SPDX-License-Identifier: MIT
*/
/*

 Copyright 2013 Google Inc. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var Xf=function(a){aa.call(this,a)};v(Xf,aa);var Yf=function(a){aa.call(this,a)};v(Yf,Xf);
/*

 Copyright 2012 Google Inc. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var Zf=function(a){var b=[];a.forEach(function(c){b.push(c>>>24&255);b.push(c>>>16&255);b.push(c>>>8&255);b.push(c&255)});return b},$f=function(a){for(var b=1,c=0;c<a.length;c++){var d=a[c];b&=("number"==typeof d&&0<=d&&255>=d&&0==d-Math.floor(d))|0}return 1==b};
var ag=function(){this.g=null},bg=function(){this.g=null};v(bg,ag);
var cg=function(){};
var dg=function(){this.blockSize=-1};
var eg=function(){this.blockSize=-1;this.blockSize=64;this.g=[];this.o=[];this.s=[];this.m=[];this.m[0]=128;for(var a=1;a<this.blockSize;++a)this.m[a]=0;this.l=this.i=0;this.reset()};v(eg,dg);eg.prototype.reset=function(){this.g[0]=1732584193;this.g[1]=4023233417;this.g[2]=2562383102;this.g[3]=271733878;this.g[4]=3285377520;this.l=this.i=0};
var fg=function(a,b,c){c||(c=0);var d=a.s;if("string"===typeof b)for(var e=0;16>e;e++)d[e]=b.charCodeAt(c)<<24|b.charCodeAt(c+1)<<16|b.charCodeAt(c+2)<<8|b.charCodeAt(c+3),c+=4;else for(e=0;16>e;e++)d[e]=b[c]<<24|b[c+1]<<16|b[c+2]<<8|b[c+3],c+=4;for(e=16;80>e;e++){var f=d[e-3]^d[e-8]^d[e-14]^d[e-16];d[e]=(f<<1|f>>>31)&4294967295}b=a.g[0];c=a.g[1];var g=a.g[2],h=a.g[3],k=a.g[4];for(e=0;80>e;e++){if(40>e)if(20>e){f=h^c&(g^h);var l=1518500249}else f=c^g^h,l=1859775393;else 60>e?(f=c&g|h&(c|g),l=2400959708):
(f=c^g^h,l=3395469782);f=(b<<5|b>>>27)+f+k+l+d[e]&4294967295;k=h;h=g;g=(c<<30|c>>>2)&4294967295;c=b;b=f}a.g[0]=a.g[0]+b&4294967295;a.g[1]=a.g[1]+c&4294967295;a.g[2]=a.g[2]+g&4294967295;a.g[3]=a.g[3]+h&4294967295;a.g[4]=a.g[4]+k&4294967295};
eg.prototype.h=function(a,b){if(null!=a){void 0===b&&(b=a.length);for(var c=b-this.blockSize,d=0,e=this.o,f=this.i;d<b;){if(0==f)for(;d<=c;)fg(this,a,d),d+=this.blockSize;if("string"===typeof a)for(;d<b;){if(e[f]=a.charCodeAt(d),++f,++d,f==this.blockSize){fg(this,e);f=0;break}}else for(;d<b;)if(e[f]=a[d],++f,++d,f==this.blockSize){fg(this,e);f=0;break}}this.i=f;this.l+=b}};
eg.prototype.j=function(){var a=[],b=8*this.l;56>this.i?this.h(this.m,56-this.i):this.h(this.m,this.blockSize-(this.i-56));for(var c=this.blockSize-1;56<=c;c--)this.o[c]=b&255,b/=256;fg(this,this.o);for(c=b=0;5>c;c++)for(var d=24;0<=d;d-=8)a[b]=this.g[c]>>d&255,++b;return a};
/*

 Copyright 2014 Google Inc. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var gg=function(a,b){return(-(a>b|0)|0)&(a^b)^b};
/*

 Copyright 2011 Google Inc. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var W=function(a){this.g=[];if(void 0!==a){if(!("function"===typeof n.Uint8Array&&a instanceof Uint8Array||$f(a)))throw new Yf("Input should be a byte array.");for(var b=a.length,c=Array((b+2)/3|0),d=0;0<=b;b-=3)c[d++]=a[b-1]&255|(a[b-2]&255)<<8|(a[b-3]&255)<<16;this.g=c}this.h=0},X=function(a){var b=new W;b.g.length=a;return b},hg=function(a){var b=new W;b.g=da(a);return b},ig=function(a){if(0>a||281474976710656<a)throw new Yf("Argument must be a valid integer.");var b=new W;do b.g.push(a&16777215),
a=Math.floor(a/16777216);while(0<a);return b},jg=function(a,b,c){c=-c|0;for(var d=gg(a.g.length,b.g.length),e=X(d),f=0;f<d;++f)e.g[f]=c&(a.g[f]^b.g[f]);for(f=0;f<d;++f)e.g[f]^=b.g[f];return e},kg=function(a){for(var b=a.g.length,c=0,d=Array(3*b);0<b;--b)d[c++]=a.g[b-1]>>>16&255,d[c++]=a.g[b-1]>>>8&255,d[c++]=a.g[b-1]&255;for(c=b=a=0;c<d.length;++c)b|=d[c],a+=!b&!d[c];return d.slice(a-(1&!b))};
W.prototype.toString=function(){var a=[],b=this,c=ig(1E6);do b=lg(b,c),a.unshift(b.ba.g[0]),b=b.fa,mg(b);while(!ng(b));return a.map(function(d,e){return 0==e||1E6<d?""+d:("000000"+d).slice(-6)}).join("")};var mg=function(a){for(var b=0,c=0,d=a.g.length-1;0<d;--d)c|=a.g[d],b+=!c&!a.g[d];a.g.length-=b;return a},og=function(a){if(0==a.h){for(var b=0,c=0,d=a.g.length-1;0<d;--d)c|=a.g[d],b+=!c&!a.g[d];c=a.g.length-b;b=24*c;c=a.g[c-1];for(c|=!c;0==(c&8388608);)c<<=1,--b;a=a.h=b}else a=a.h;return a};
W.prototype.add=function(a){for(var b=gg(this.g.length,a.g.length),c=X(b+1),d=0,e=0;e<b;++e)d+=(this.g[e]|0)+(a.g[e]|0),c.g[e]=d&16777215,d>>=24;c.g[b]=d;return c};
var lg=function(a,b){var c=og(b),d=(c+24-1)/24|0;c=24*d-c;b=pg(b,c);var e=jg(hg(a.g),pg(a,c),0==c|0);a=jg(qg,X(e.g.length+1),0>=e.g.length+1-d|0);e.g.push(0);for(var f=e.g.length-d-1;0<=f;f--){var g=b.g.length,h=16777216*e.g[g+f]+e.g[g+f-1];var k=b.g[g-1];var l=Math.floor(h/k);k=l-(16777216==l|l*(b.g[g-2]|0)>16777216*(h-l*k)+(e.g[g+f-2]|0));g=0;a.g[f]=k;for(h=0;h<=d;h++)g+=e.g[h+f]-(b.g[h]|0)*k,e.g[h+f]=g&16777215,g=Math.floor(g/16777216);k=g;g=0;a.g[f]+=k;for(h=0;h<=d;h++)g+=e.g[h+f]+(b.g[h]&k),
e.g[h+f]=g&16777215,g>>=24}if(0>c||23<c)throw new Yf("Illegal shift value.");h=e.g.length;b=X(h);f=(1<<c)-1;g=0;for(--h;0<=h;h--)b.g[h]=g+(e.g[h]>>c),g=(e.g[h]&f)<<24-c;c=X(d);for(e=0;e<d;e++)c.g[e]=b.g[e]|0;e=c;mg(a);return{fa:a,ba:e}},ng=function(a){for(var b=qg,c=0,d=0,e=0,f=0,g=gg(a.g.length,b.g.length)-1;0<=g;--g){var h=a.g[g]|0,k=b.g[g]|0;d|=h<k;c|=h>k&!d;e|=h>k;f|=h<k&!e}return 0==c-f};
W.prototype.and=function(a){for(var b=gg(this.g.length,a.g.length),c=X(b);0<=b;--b)c.g[b]=(this.g[b]|0)&(a.g[b]|0);return c};W.prototype.or=function(a){for(var b=gg(this.g.length,a.g.length),c=X(b);0<=b;--b)c.g[b]=this.g[b]|0|a.g[b]|0;return c};W.prototype.xor=function(a){for(var b=gg(this.g.length,a.g.length),c=X(b);0<=b;--b)c.g[b]=(this.g[b]|0)^(a.g[b]|0);return c};
var pg=function(a,b){if(0>b||23<b)throw new Yf("Illegal shift value.");for(var c=a.g.length,d=X(c+1),e=(1<<b)-1,f=(1<<24-b)-1,g=0,h=0;h<c;h++)d.g[h]=((a.g[h]&f)<<b)+g,g=a.g[h]>>24-b&e;d.g[c]=g;return mg(d)},qg=ig(0);ig(1);ig(2);
var sg=function(a,b){W.call(this,a);mg(this);a=1;for(var c=this.g[0],d=1;16777216>d;d<<=1)a*c&d&&(a|=d);this.j=16777216-a;if(void 0!==b)b=new W(b);else{b=this.g.length;a=X(2*b+1);for(c=0;c<2*b;++c)a.g[c]=0;a.g[2*b]=1;b=lg(a,this).ba}this.l=b;this.i=rg(this,this.l)};v(sg,W);
sg.prototype.pow=function(a,b){a=new W(a);b instanceof W&&(b=kg(b));var c=Y(this,a,this.l);a=Array(16);a[0]=this.i;for(var d=1;16>d;++d)a[d]=Y(this,c,a[d-1]);c=X(this.g.length);d=hg(this.i.g);for(var e=b.length,f=0;f<e;++f)Y(this,d,d,c),Y(this,c,c,d),Y(this,d,d,c),Y(this,c,c,d),Y(this,d,a[b[f]>>4&15],c),Y(this,c,c,d),Y(this,d,d,c),Y(this,c,c,d),Y(this,d,d,c),Y(this,c,a[b[f]&15],d);rg(this,d,c);return kg(c)};
var rg=function(a,b,c){var d=a.g.length;c=c||X(d);for(var e=0;e<d;++e)c.g[e]=b.g[e];for(e=0;e<d;++e){b=a;var f=c,g=f.g[0],h=g*b.j&16777215;g+=h*b.g[0];for(var k=1,l=b.g.length;k<l;++k)g=(g/16777216|0)+f.g[k]+h*b.g[k],f.g[k-1]=g&16777215;f.g[k-1]=g/16777216|0}tg(a,c,d);return c},Y=function(a,b,c,d){var e=a.g.length;d=d||X(e);for(var f=0;f<e;++f)d.g[f]=0;for(f=0;f<e;++f){var g=a,h=b.g[f]|0,k=c,l=d,p=h*k.g[0]+l.g[0],w=(p&16777215)*g.j&16777215;p+=w*g.g[0];for(var B=1,u=g.g.length;B<u;++B)p=(p/16777216|
0)+h*(k.g[B]|0)+l.g[B]+w*g.g[B],l.g[B-1]=p&16777215;l.g[B-1]=p/16777216|0}tg(a,d,e);return d},tg=function(a,b,c){for(var d=0,e=0;e<c;++e)d+=b.g[e]-a.g[e],b.g[e]=d&16777215,d>>=24;var f=d>>24;for(e=d=0;e<c;++e)d+=b.g[e]+(a.g[e]&f),b.g[e]=d&16777215,d>>=24};
var ug=function(a,b,c){this.i=a;this.l=this.h=b;this.g=null;this.modulusLength=0;this.g=new sg(a,c);this.modulusLength=Math.ceil(og(this.g)/8)};t(ug,cg);
var xg=function(a,b){this.blockSize=-1;this.blockSize=64;this.l=n.Uint8Array?new Uint8Array(this.blockSize):Array(this.blockSize);this.m=this.i=0;this.g=[];this.s=a;this.o=b;this.v=n.Int32Array?new Int32Array(64):Array(64);void 0===vg&&(n.Int32Array?vg=new Int32Array(wg):vg=wg);this.reset()},vg;v(xg,dg);for(var yg=[],zg=0;63>zg;zg++)yg[zg]=0;var Ag=function(a){return Array.prototype.concat.apply([],arguments)}(128,yg);
xg.prototype.reset=function(){this.m=this.i=0;this.g=n.Int32Array?new Int32Array(this.o):da(this.o)};
var Bg=function(a){for(var b=a.l,c=a.v,d=0,e=0;e<b.length;)c[d++]=b[e]<<24|b[e+1]<<16|b[e+2]<<8|b[e+3],e=4*d;for(b=16;64>b;b++){e=c[b-15]|0;d=c[b-2]|0;var f=(c[b-16]|0)+((e>>>7|e<<25)^(e>>>18|e<<14)^e>>>3)|0,g=(c[b-7]|0)+((d>>>17|d<<15)^(d>>>19|d<<13)^d>>>10)|0;c[b]=f+g|0}d=a.g[0]|0;e=a.g[1]|0;var h=a.g[2]|0,k=a.g[3]|0,l=a.g[4]|0,p=a.g[5]|0,w=a.g[6]|0;f=a.g[7]|0;for(b=0;64>b;b++){var B=((d>>>2|d<<30)^(d>>>13|d<<19)^(d>>>22|d<<10))+(d&e^d&h^e&h)|0;g=l&p^~l&w;f=f+((l>>>6|l<<26)^(l>>>11|l<<21)^(l>>>
25|l<<7))|0;g=g+(vg[b]|0)|0;g=f+(g+(c[b]|0)|0)|0;f=w;w=p;p=l;l=k+g|0;k=h;h=e;e=d;d=g+B|0}a.g[0]=a.g[0]+d|0;a.g[1]=a.g[1]+e|0;a.g[2]=a.g[2]+h|0;a.g[3]=a.g[3]+k|0;a.g[4]=a.g[4]+l|0;a.g[5]=a.g[5]+p|0;a.g[6]=a.g[6]+w|0;a.g[7]=a.g[7]+f|0};
xg.prototype.h=function(a,b){void 0===b&&(b=a.length);var c=0,d=this.i;if("string"===typeof a)for(;c<b;)this.l[d++]=a.charCodeAt(c++),d==this.blockSize&&(Bg(this),d=0);else if(ea(a))for(;c<b;){var e=a[c++];if(!("number"==typeof e&&0<=e&&255>=e&&e==(e|0)))throw Error("K");this.l[d++]=e;d==this.blockSize&&(Bg(this),d=0)}else throw Error("L");this.i=d;this.m+=b};
xg.prototype.j=function(){var a=[],b=8*this.m;56>this.i?this.h(Ag,56-this.i):this.h(Ag,this.blockSize-(this.i-56));for(var c=63;56<=c;c--)this.l[c]=b&255,b/=256;Bg(this);for(c=b=0;c<this.s;c++)for(var d=24;0<=d;d-=8)a[b++]=this.g[c]>>d&255;return a};
var wg=[1116352408,1899447441,3049323471,3921009573,961987163,1508970993,2453635748,2870763221,3624381080,310598401,607225278,1426881987,1925078388,2162078206,2614888103,3248222580,3835390401,4022224774,264347078,604807628,770255983,1249150122,1555081692,1996064986,2554220882,2821834349,2952996808,3210313671,3336571891,3584528711,113926993,338241895,666307205,773529912,1294757372,1396182291,1695183700,1986661051,2177026350,2456956037,2730485921,2820302411,3259730800,3345764771,3516065817,3600352804,
4094571909,275423344,430227734,506948616,659060556,883997877,958139571,1322822218,1537002063,1747873779,1955562222,2024104815,2227730452,2361852424,2428436474,2756734187,3204031479,3329325298];
var Dg=function(){xg.call(this,8,Cg)};v(Dg,xg);var Cg=[1779033703,3144134277,1013904242,2773480762,1359893119,2600822924,528734635,1541459225];
for(var Eg=[1116352408,3609767458,1899447441,602891725,3049323471,3964484399,3921009573,2173295548,961987163,4081628472,1508970993,3053834265,2453635748,2937671579,2870763221,3664609560,3624381080,2734883394,310598401,1164996542,607225278,1323610764,1426881987,3590304994,1925078388,4068182383,2162078206,991336113,2614888103,633803317,3248222580,3479774868,3835390401,2666613458,4022224774,944711139,264347078,2341262773,604807628,2007800933,770255983,1495990901,1249150122,1856431235,1555081692,3175218132,
1996064986,2198950837,2554220882,3999719339,2821834349,766784016,2952996808,2566594879,3210313671,3203337956,3336571891,1034457026,3584528711,2466948901,113926993,3758326383,338241895,168717936,666307205,1188179964,773529912,1546045734,1294757372,1522805485,1396182291,2643833823,1695183700,2343527390,1986661051,1014477480,2177026350,1206759142,2456956037,344077627,2730485921,1290863460,2820302411,3158454273,3259730800,3505952657,3345764771,106217008,3516065817,3606008344,3600352804,1432725776,4094571909,
1467031594,275423344,851169720,430227734,3100823752,506948616,1363258195,659060556,3750685593,883997877,3785050280,958139571,3318307427,1322822218,3812723403,1537002063,2003034995,1747873779,3602036899,1955562222,1575990012,2024104815,1125592928,2227730452,2716904306,2361852424,442776044,2428436474,593698344,2756734187,3733110249,3204031479,2999351573,3329325298,3815920427,3391569614,3928383900,3515267271,566280711,3940187606,3454069534,4118630271,4000239992,116418474,1914138554,174292421,2731055270,
289380356,3203993006,460393269,320620315,685471733,587496836,852142971,1086792851,1017036298,365543100,1126000580,2618297676,1288033470,3409855158,1501505948,4234509866,1607167915,987167468,1816402316,1246189591],Fg=[],Gg=0;Gg<Eg.length;Gg+=2)Fg.push(new Kf(Eg[Gg+1],Eg[Gg]));
var Ig=function(){this.blockSize=-1};v(Ig,dg);Ig.prototype.reset=function(){this.g.reset()};Ig.prototype.j=function(){return this.g.j()};Ig.prototype.h=function(a,b){this.g.h(a,b)};Ig.prototype.hash=function(a){this.reset();this.h(a);return this.j()};
var Jg=function(){this.blockSize=-1;this.g=new Dg;this.blockSize=this.g.blockSize};t(Jg,Ig);Jg.prototype.i="SHA256";
var Kg=function(a){aa.call(this,a)};t(Kg,aa);
var Lg={MD5:[48,32,48,12,6,8,42,134,72,134,247,13,2,5,5,0,4,16],RIPEMD160:[48,33,48,9,6,5,43,36,3,2,1,5,0,4,20],SHA1:[48,33,48,9,6,5,43,14,3,2,26,5,0,4,20],SHA224:[48,45,48,13,6,9,96,134,72,1,101,3,4,2,4,5,0,4,28],SHA256:[48,49,48,13,6,9,96,134,72,1,101,3,4,2,1,5,0,4,32],SHA384:[48,65,48,13,6,9,96,134,72,1,101,3,4,2,2,5,0,4,48],SHA512:[48,81,48,13,6,9,96,134,72,1,101,3,4,2,3,5,0,4,64]};
var Mg=function(a,b,c,d){ug.call(this,a,b,c);this.j=d||new Jg};t(Mg,ug);
var Ng=function(a,b,c,d){this.g=null;this.h=new Mg(a,b,c,d)};t(Ng,bg);
var Og=function(a){this.g=a};
var Pg=function(a,b){this.g=new Og(new Ng(a,b))};
var Qg=function(a,b,c,d,e){this.g="U";this.h=0;a&&(a=a.split(","))&&2==a.length&&(this.g=a[0],this.h=parseInt(a[1],10));if(0>=b||0>=c||0>=d)throw Error("M");this.m=b;this.i=c;this.l=d;this.j=e},Rg=function(a){switch(a.g){case "Y":return a.m;case "N":return a.i;case "P":return a.j;default:return a.l}},Sg=function(a,b,c,d,e,f){this.l=new Pg(Xb(a),Xb(b));this.j=c;this.g=d;this.i=e;this.h=f};
var Tg=function(a,b,c,d,e,f,g,h){this.g=a||"";this.h=new Sg(b||"",c||"",e||1,f||1,g||1,h||1);this.i=d||""},Ug=function(a){var b=(new rf(document)).get(a.g,"");if(b){var c=a.h;var d=c.l;a=bb(a.i);b=Xb(b.substr(b.indexOf(":")+1));d=d.g;var e=d.g;if(!e.g){var f=new eg;f.h(Zf([e.h.i.length]));f.h(e.h.i);f.h(Zf([e.h.h.length]));f.h(e.h.h);f=f.j();var g=Array(5);g[0]=0;g[1]=f[0];g[2]=f[1];g[3]=f[2];g[4]=f[3];e.g=g}e=e.g;b:if(f=ha(b,0,e.length),ea(e)&&ea(f)&&e.length==f.length){g=e.length;for(var h=0;h<
g;h++)if(e[h]!==f[h]){f=!1;break b}f=!0}else f=!1;if(f){f=e.length+4;e=ha(b,e.length,f);g=[];for(h=0;h<e.length;h+=4)g.push((e[h+3]|e[h+2]<<8|e[h+1]<<16|e[h]<<24)>>>0);g=g[0];if(f+g>b.length)b=null;else{e=ha(b,f,f+g);a=ia(e,Zf([a.length]),a,b[0]);d=d.g.h;b=d.g.pow(ha(b,f+g),d.l);f=d.j;d=d.modulusLength-1;g=f.hash(a);a=[];if(void 0===Lg[f.i])throw new Kg("invalid hash for signature");fa(a,Lg[f.i]);fa(a,g);f=a.length;if(d<f+11)throw new Kg("intended encoded message length too short");d=Array(d-f-3+
1).fill(255);a=[1].concat(d,[0],a);if(a.length===b.length&&$f(a)&&$f(b)){d=1;for(f=0;f<a.length;f++)d&=!(a[f]^b[f])|0;b=1==d}else b=!1;b=b?e:null}}else b=null;if(b)if(8192>=b.length)b=String.fromCharCode.apply(null,b);else{a="";for(d=0;d<b.length;d+=8192)a+=String.fromCharCode.apply(null,Array.prototype.slice.call(b,d,d+8192));b=a}else b=null;c=new Qg(b,c.j,c.g,c.i,c.h)}else c=null;return c?"Y"==c.g&&!(c.h+Rg(c)<Date.now()):!1};
var Vg=function(a,b,c,d,e,f){try{var g=a.g,h=Oe(a.g,"SCRIPT");h.async=!0;h.src=lb(b);Ca(h);g.head.appendChild(h);h.addEventListener("load",function(){e();d&&g.head.removeChild(h)});h.addEventListener("error",function(){0<c?Vg(a,b,c-1,d,e,f):(d&&g.head.removeChild(h),f())})}catch(k){f()}},Wg=function(a,b,c,d){Vg(a?new Pe(9==a.nodeType?a:a.ownerDocument||a.document):ab||(ab=new Pe),b,0,!1,void 0===c?function(){}:c,void 0===d?function(){}:d)};
var Xg=function(a){return a?mb(C(a,4)||""):null};
var Zg=function(a){A.call(this,a,-1,Yg)};t(Zg,A);var $g=function(){var a=new Zg;C(a,2).push(7);return a},Yg=[2];
var ah=function(a){A.call(this,a)};t(ah,A);ah.prototype.getTimestamp=function(){return I(this,wc,7)};var bh=function(a){A.call(this,a)};t(bh,A);var dh=function(a){A.call(this,a,-1,ch)};t(dh,A);var eh=function(a){A.call(this,a)};t(eh,A);var fh=function(a){A.call(this,a)};t(fh,A);var gh=function(a){A.call(this,a)};t(gh,A);var hh=function(a){A.call(this,a)};t(hh,A);var ch=[1,2];
var ih={},jh=(ih.ab=1,ih.gdpr=2,ih.consent=2,ih.ccpa=3,ih),kh=function(){this.g=new ah},lh=function(a){if(!D(a.g,3)){a=a.g;var b=new eh;K(a,3,b)}},mh=function(a){if(!D(a.g,4)){a=a.g;var b=new fh;K(a,4,b)}},nh=function(a){if(!D(a.g,5)){a=a.g;var b=new gh;K(a,5,b)}};
/*

Math.uuid.js (v1.4)
http://www.broofa.com
mailto:robert@broofa.com
Copyright (c) 2010 Robert Kieffer
Dual licensed under the MIT and GPL licenses.
*/
var oh="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".split(""),ph=function(){for(var a=Array(36),b=0,c,d=0;36>d;d++)8==d||13==d||18==d||23==d?a[d]="-":14==d?a[d]="4":(2>=b&&(b=33554432+16777216*Math.random()|0),c=b&15,b>>=4,a[d]=oh[19==d?c&3|8:c]);return a.join("")};
var qh=function(a,b){this.h=a;this.g=b},rh=function(a){var b=(b=Df(a))&&D(b,1)?C(b,1):null;var c=(c=Df(a))&&D(c,2)?C(c,2):null;a=(a=Df(a))&&D(a,3)?C(a,3):null;if(null==b||null==c||null==a)return null;a=qd(b);var d=Uc(c);return a&&d?new qh(b,c):null};
var sh=function(a){try{var b=Ef(a);return b?N(If,b):null}catch(c){return null}};
var th=function(a){a=(void 0===a?null:a)||n;return a.googlefc||(a.googlefc={})},uh=function(a,b,c){c=void 0===c?!1:c;var d=th(null);if(!d.hasOwnProperty(a)||c)d[a]=b};
uh("ConsentStatusEnum",{UNKNOWN:0,CONSENTED_TO_PERSONALIZED_ADS:1,CONSENTED_TO_NON_PERSONALIZED_ADS:2,CONTRIBUTOR:3,NO_CONSENT:4,CONSENT_NOT_REQUIRED:5});uh("AdBlockerStatusEnum",{UNKNOWN:0,EXTENSION_LEVEL_AD_BLOCKER:1,NETWORK_LEVEL_AD_BLOCKER:2,NO_AD_BLOCKER:3});uh("WhitelistStatusEnum",{UNKNOWN:0,NOT_WHITELISTED:1,WHITELISTED:2});uh("AllowAdsStatusEnum",{UNKNOWN:0,ADS_NOT_ALLOWED:1,ADS_ALLOWED:2});
var vh=function(a){A.call(this,a)};t(vh,A);
var xh=function(a){A.call(this,a,-1,wh)};t(xh,A);var wh=[1];
var yh=function(a){A.call(this,a)};t(yh,A);
var zh={va:"loaded",ga:"getM25Consent"};
var Ah=function(a){A.call(this,a)};t(Ah,A);var Bh=function(a){var b=new Ah;return F(b,1,a)},Ch=function(a,b){return F(a,3,b)};
var Eh=function(a){A.call(this,a,-1,Dh)};t(Eh,A);var Dh=[1,2];
var Fh=function(a){A.call(this,a)};t(Fh,A);var Gh=function(a){var b=new Fh;return F(b,1,a)};
var Hh=function(a){A.call(this,a)};t(Hh,A);var Ih=function(a,b){return K(a,2,b)};
var Jh=function(){this.i=this.g=null;this.h=!1};m=Jh.prototype;m.setCmpModeObject=function(a){try{this.g=N(Ah,a)}catch(b){}};m.setM25ConsentObject=function(a){try{this.i=N(Eh,a)}catch(b){}};m.getSerializedReturnMessageForCommand=function(a){if(this.h)return M(Ih(new Hh,Gh(4)));switch(a){case "loaded":return a=new Hh,a=K(a,3,this.g),M(Ih(a,Gh(1)));case "getM25Consent":return a=new Hh,a=K(a,4,this.i),M(Ih(a,Gh(1)));default:return this.getSerializedReturnMessageForInvalidCommand()}};
m.getSerializedReturnMessageForInvalidCommand=function(){return M(Ih(new Hh,Gh(2)))};m.setError=function(){this.h=!0};var Kh=function(a){a.__fcInternalApiManager=a.__fcInternalApiManager||new Jh;return a.__fcInternalApiManager};
var Lh=function(a){this.h=Kh(a);this.g={};this.i={}};Lh.prototype.push=function(a,b){Mh(a)?this.i[a]?(a=this.h.getSerializedReturnMessageForCommand(a),"function"===typeof b&&b(a)):(this.g[a]=this.g[a]||[],this.g[a].push(b)):(a=this.h.getSerializedReturnMessageForInvalidCommand(),"function"===typeof b&&b(a))};Lh.prototype.executeCommandType=function(a){if(Mh(a)){this.i[a]=!0;for(var b=this.g[a]||[];0<b.length;)this.push(a,b.shift())}};
Lh.prototype.executeAllRemainingCommands=function(){for(var a=r(Object.values(zh)),b=a.next();!b.done;b=a.next())this.executeCommandType(b.value)};var Mh=function(a){return-1!==Object.values(zh).indexOf(a)},Nh=function(a){var b=th(a).__fci||[];if(!Array.isArray(b))return b;a=new Lh(a);if(0===b.length%2)for(var c=0;c<b.length-1;c+=2)a.push(b[c],b[c+1]);uh("__fci",a,!0);return a};
var Oh=function(a){this.g=a;this.h=Kh(this.g);this.i=Nh(this.g)};
var Ph=Fb?mb(hb(new gb(eb,'javascript:""'))):mb(hb(new gb(eb,"about:blank"))),Qh=function(){this.g=new Pe(n.top.document)},Sh=function(a,b){if(!Rh(a,b)){var c=Oe(a.g.g,"IFRAME");c.name=b;c.src=lb(Ph).toString();c.style.display="none";c.style.width="0px";c.style.height="0px";c.style.border="none";c.style.zIndex="-1000";c.style.left="-1000px";c.style.top="-1000px";var d=function(){a.g.g.body?a.g.g.body.appendChild(c):n.setTimeout(d,5)};d()}},Rh=function(a,b){return cb(a.g.g.getElementsByTagName("IFRAME"),
function(c){return c.name===b})};
var Th=window.URL,Uh;try{new Th("http://example.com"),Uh=!0}catch(a){Uh=!1}var Vh=Uh,Wh=function(a){this.g=new Map;0==a.indexOf("?")&&(a=a.substring(1));a=r(a.split("&"));for(var b=a.next();!b.done;b=a.next()){var c=b.value;b=c;var d="";c=c.split("=");1<c.length&&(b=decodeURIComponent(c[0].replace("+"," ")),d=decodeURIComponent(c[1].replace("+"," ")));c=this.g.get(b);null==c&&(c=[],this.g.set(b,c));c.push(d)}};Wh.prototype.get=function(a){return(a=this.g.get(a))&&a.length?a[0]:null};
Wh.prototype.getAll=function(a){return[].concat(Ia(this.g.get(a)||[]))};Wh.prototype.has=function(a){return this.g.has(a)};Wh.prototype[Symbol.iterator]=function(){return Be.apply(null,Ia(ze(this.g,function(a){var b=a[0];return ze(a[1],function(c){return[b,c]})})))};Wh.prototype.toString=function(){return Xh(this)};
var Xh=function(a){var b=function(c){return encodeURIComponent(c).replace(/[!()~']|(%20)/g,function(d){return{"!":"%21","(":"%28",")":"%29","%20":"+","'":"%27","~":"%7E"}[d]})};return Array.from(a,function(c){return b(c[0])+"="+b(c[1])}).join("&")},Zh=function(a){if(Vh){try{var b=new Th(a)}catch(f){throw Error("N`"+a);}var c=Yh.get(b.protocol);if(!c)throw Error("N`"+a);if(!b.hostname)throw Error("N`"+a);"null"!=b.origin?a=b:(a={href:b.href,protocol:b.protocol,username:"",password:"",host:b.host,port:b.port,
hostname:b.hostname,pathname:b.pathname,search:b.search,hash:b.hash},a.origin=c===b.port?b.protocol+"//"+b.hostname:b.protocol+"//"+b.hostname+":"+b.port);return a}b=Oe(document,"A");try{var d=new x(a,rb);if(d instanceof x)var e=d;else d instanceof x?e=d:(d="object"==typeof d&&d.h?d.g():String(d),tb.test(d)||(d="about:invalid#zClosurez"),e=new x(d,rb));b.href=sb(e);c=b.protocol}catch(f){throw Error("N`"+a);}if(""===c||":"===c||":"!=c[c.length-1])throw Error("N`"+a);if(!Yh.has(c))throw Error("N`"+
a);if(!b.hostname)throw Error("N`"+a);a={href:b.href,protocol:b.protocol,username:"",password:"",hostname:b.hostname,pathname:"/"+b.pathname,search:b.search,hash:b.hash};Yh.get(b.protocol)===b.port?(a.host=a.hostname,a.port="",a.origin=a.protocol+"//"+a.hostname):(a.host=b.host,a.port=b.port,a.origin=a.protocol+"//"+a.hostname+":"+a.port);return a},Yh=new Map([["http:","80"],["https:","443"],["ws:","80"],["wss:","443"],["ftp:","21"]]),$h=function(a){return Vh&&a.searchParams?a.searchParams:new Wh(a.search)};
var ai=function(a){var b=$h(Zh(a.location.href));a=b.get("fcconsent");b=b.get("fc");return"alwaysshow"===b?b:"alwaysshow"===a?a:null},bi=function(a){a=$h(Zh(a.location.href)).get("fctype");return"ab"===a||"gdpr"===a||"consent"===a||"ccpa"===a?a:null};
var ci=function(a,b,c){this.g=a.document;this.h=new Qh;this.j=new Oh(a);a=c?c:new ef(null);this.i=new Jf(this.g,b,a)},di=function(a){var b=sh(a.g);b=b?((a=sh(a.g))?0<C(a,2).length||0<C(a,1).length:!1)&&!cc(b,7):!1;return b},ei=function(a,b,c){b.forEach(function(d){Sh(a.h,"googlefcPA-"+d)});(b.length||c.length)&&Sh(a.h,"googlefcNPA")};
var fi=function(a){this.g=a};
var gi=function(a){this.h=this.o=this.j="";this.s=null;this.i=this.g="";this.l=!1;var b;a instanceof gi?(this.l=a.l,hi(this,a.j),this.o=a.o,this.h=a.h,ii(this,a.s),this.g=a.g,ji(this,ki(a.m)),this.i=a.i):a&&(b=String(a).match(Re))?(this.l=!1,hi(this,b[1]||"",!0),this.o=li(b[2]||""),this.h=li(b[3]||"",!0),ii(this,b[4]),this.g=li(b[5]||"",!0),ji(this,b[6]||"",!0),this.i=li(b[7]||"")):(this.l=!1,this.m=new mi(null,this.l))};
gi.prototype.toString=function(){var a=[],b=this.j;b&&a.push(ni(b,oi,!0),":");var c=this.h;if(c||"file"==b)a.push("//"),(b=this.o)&&a.push(ni(b,oi,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.s,null!=c&&a.push(":",String(c));if(c=this.g)this.h&&"/"!=c.charAt(0)&&a.push("/"),a.push(ni(c,"/"==c.charAt(0)?pi:qi,!0));(c=this.m.toString())&&a.push("?",c);(c=this.i)&&a.push("#",ni(c,ri));return a.join("")};
gi.prototype.resolve=function(a){var b=new gi(this),c=!!a.j;c?hi(b,a.j):c=!!a.o;c?b.o=a.o:c=!!a.h;c?b.h=a.h:c=null!=a.s;var d=a.g;if(c)ii(b,a.s);else if(c=!!a.g){if("/"!=d.charAt(0))if(this.h&&!this.g)d="/"+d;else{var e=b.g.lastIndexOf("/");-1!=e&&(d=b.g.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var f=[],g=0;g<e.length;){var h=e[g++];"."==h?d&&g==e.length&&f.push(""):".."==h?((1<f.length||1==f.length&&
""!=f[0])&&f.pop(),d&&g==e.length&&f.push("")):(f.push(h),d=!0)}d=f.join("/")}else d=e}c?b.g=d:c=""!==a.m.toString();c?ji(b,ki(a.m)):c=!!a.i;c&&(b.i=a.i);return b};
var hi=function(a,b,c){a.j=c?li(b,!0):b;a.j&&(a.j=a.j.replace(/:$/,""))},ii=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("O`"+b);a.s=b}else a.s=null},ji=function(a,b,c){b instanceof mi?(a.m=b,si(a.m,a.l)):(c||(b=ni(b,ti)),a.m=new mi(b,a.l))},li=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},ni=function(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,ui),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},ui=function(a){a=a.charCodeAt(0);
return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},oi=/[#\/\?@]/g,qi=/[#\?:]/g,pi=/[#\?]/g,ti=/[#\?@]/g,ri=/#/g,mi=function(a,b){this.h=this.g=null;this.i=a||null;this.j=!!b},vi=function(a){a.g||(a.g=new S,a.h=0,a.i&&Se(a.i,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))};mi.prototype.add=function(a,b){vi(this);this.i=null;a=wi(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.h+=1;return this};
var xi=function(a,b){vi(a);b=wi(a,b);a.g.has(b)&&(a.i=null,a.h-=a.g.get(b).length,a=a.g,Ke(a.h,b)&&(delete a.h[b],--a.size,a.i++,a.g.length>2*a.size&&Je(a)))};mi.prototype.isEmpty=function(){vi(this);return 0==this.h};var yi=function(a,b){vi(a);b=wi(a,b);return a.g.has(b)};m=mi.prototype;m.forEach=function(a,b){vi(this);this.g.forEach(function(c,d){c.forEach(function(e){a.call(b,e,d,this)},this)},this)};
m.G=function(){vi(this);for(var a=this.g.F(),b=this.g.G(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};m.F=function(a){vi(this);var b=[];if("string"===typeof a)yi(this,a)&&(b=b.concat(this.g.get(wi(this,a))));else{a=this.g.F();for(var c=0;c<a.length;c++)b=b.concat(a[c])}return b};m.set=function(a,b){vi(this);this.i=null;a=wi(this,a);yi(this,a)&&(this.h-=this.g.get(a).length);this.g.set(a,[b]);this.h+=1;return this};
m.get=function(a,b){if(!a)return b;a=this.F(a);return 0<a.length?String(a[0]):b};m.toString=function(){if(this.i)return this.i;if(!this.g)return"";for(var a=[],b=this.g.G(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.F(d);for(var f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}}return this.i=a.join("&")};
var ki=function(a){var b=new mi;b.i=a.i;a.g&&(b.g=new S(a.g),b.h=a.h);return b},wi=function(a,b){b=String(b);a.j&&(b=b.toLowerCase());return b},si=function(a,b){b&&!a.j&&(vi(a),a.i=null,a.g.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(xi(this,d),xi(this,e),0<c.length&&(this.i=null,this.g.set(wi(this,e),da(c)),this.h+=c.length))},a));a.j=b};
var zi=function(a,b){this.g=a;this.h=void 0===b?null:b;this.l=this.O=this.L=this.j=this.I=this.J=this.i=this.s=null;this.B=0;this.m=this.o=this.v=this.D=this.K=this.A=this.C=null},Ai=function(a){var b=a.g.document,c=new ef(a.h?I(a.h.g,Od,4):null),d,e,f;var g=null!=(f=null==(d=Af(b))?void 0:null==(e=I(d,lf,1))?void 0:C(e,1))?f:null;if(wd(vf)){d=!!g;var h,k,l;e=null!=(l=null==(h=Bf(b))?void 0:null==(k=I(h,qf,1))?void 0:C(k,1))?l:null;Gf(d,!!e,d&&!!e&&g==e,c)}if(wd(uf)){var p,w,B;b=null!=(B=null==(p=
Bf(b))?void 0:null==(w=I(p,qf,1))?void 0:C(w,1))?B:null;g=null!=b?b:g}a.s=g;a.i=rh(a.g.document);a.i&&(a.J=a.i.h,a.I=a.i.g);a.j=Ff(a.g.document);a.j&&(a.L=C(a.j,2),a.O=I(a.j,wc,1));var u;p=new ef(a.h?I(a.h.g,Od,4):null);w=a.g.document;var T,R;g=null!=(R=null==(T=Af(w))?void 0:I(T,hf,6))?R:null;if(wd(vf)){T=!!g;var L,Z;R=null!=(Z=null==(L=Bf(w))?void 0:I(L,hf,2))?Z:null;L=T&&!!R&&hc(g,R);Gf(T,!!R,L,p)}if(wd(uf)){var ka;L=null!=(ka=null==(u=Bf(w))?void 0:I(u,hf,2))?ka:null;u=null!=L?L:g}else u=g;u&&
D(u,1)?(u=I(u,jf,1))&&D(u,1)?(ka=I(u,wc,2),L=Date.now(),u=!ka||L/1E3<E(ka,1,0)?null:u):u=null:u=null;a.l=u;(u=a.h?I(a.h.g,gf,2):null)&&!hc(u,new gf)&&(a.B=Ug(new Tg(C(u,1),C(u,5),C(u,4),C(u,6),C(u,8),C(u,9),C(u,10),C(u,11)))?1:2);a.C=sh(a.g.document);u=new gi(a.g.location.href);ji(u,new mi);u.i="";1E3>=u.toString().length&&(a.D=u.toString())},Bi=function(a,b){var c=new kh;a.B&&F(c.g,6,a.B);if(a.s){var d=a.s;if(d){if(!D(c.g,1)){var e=c.g,f=new bh;K(e,1,f)}e=I(c.g,bh,1);F(e,1,d)}}if(a.i){if(d=a.J)lh(c),
e=I(c.g,eh,3),F(e,1,d);if(d=a.I)lh(c),e=I(c.g,eh,3),F(e,2,d)}if(a.j){if(d=a.O)mh(c),e=I(c.g,fh,4),K(e,1,d);if(d=a.L)mh(c),e=I(c.g,fh,4),F(e,2,d)}if(a.l){if(d=C(a.l,1))nh(c),e=I(c.g,gh,5),F(e,1,d);if(d=I(a.l,wc,2))nh(c),e=I(c.g,gh,5),K(e,2,d)}a.o&&F(c.g,8,a.o);a.m&&F(c.g,9,a.m);a.A&&(d=a.K||"","alwaysshow"===a.A&&(e=c.g,f=new hh,f=F(f,1,1),K(e,10,f),d=jh[d]))&&(e=I(c.g,hh,10),F(e,2,d));if(a.C&&(d=a.C)){e=c.g;f=new dh;var g=C(d,1);f=G(f,1,g);g=C(d,2);f=G(f,2,g);K(e,2,f);D(d,6)&&(e=I(c.g,dh,2),d=xc(new Date(C(d,
6))),K(e,3,d))}a.D&&(d=a.D)&&F(c.g,12,d);a.v&&(d=c.g,e=a.v,a=e.constructor,e=oa(J(e)),a=Aa(a,e),K(d,11,a));hc(c.g,new ah)||(a=c.g,d=xc(new Date(Date.now())),K(a,7,d),c={fccs:sa(bb(M(c.g)),4)},b=ob(b,c));return b};
var Di=function(a){return new Promise(function(b,c){var d=th().controlledMessagingFunction;if(null==d)c(!1);else{var e=new Ed;if("function"!==typeof d)F(e,1,!1),Ci(e,a),c(!1);else{F(e,1,!0);var f={proceed:function(h){var k=new Ed;k=F(k,1,!0);var l=new Gd,p=!0;void 0===h?F(l,1,1):"boolean"!==typeof h?F(l,1,2):(F(l,1,h?3:4),p=h);fc(k,3,Dd[0],l);Ci(k,a);b(p)}},g=new Fd;try{d(f)}catch(h){F(g,1,!0);fc(e,2,Dd[0],g);Ci(e,a);c(!1);return}F(g,1,!1);fc(e,2,Dd[0],g);Ci(e,a)}}})},Ci=function(a,b){var c=new Cd;
a=K(c,2,a);c=new Md;a=fc(c,8,Ld[0],a);ff(b,a)};
var Ei,Fi=jc(1);Ei=H(Fi,2,0,0);var Gi;Gi=H(Ei,3,0,0);var Hi;Hi=H(Gi,4,0,0);var Ii=function(a){this.g=a||Hi};Ii.prototype.h=function(a,b,c){"function"===typeof c&&(1!==b?c(null,!1):"getUSPData"===a&&(a=this.g,a=[E(a,1,0),mc[E(a,2,0)],mc[E(a,3,0)],mc[E(a,4,0)]].join(""),(a=nc(a)?a:null)?c({version:1,uspString:a},!0):c(null,!1)))};
var Ji=function(a){this.g=a};Ji.prototype.setUsPrivacyProto=function(a){try{var b=N(ic,a);this.g.g=b;return!0}catch(c){return!1}};
var Ki=function(a,b){this.i=a;b?(a=b.toUpperCase(),nc(a)?(b=jc(parseInt(a[0],10)),b=H(b,2,kc[a[1]],0),b=H(b,3,kc[a[2]],0),a=H(b,4,kc[a[3]],0)):a=null):a=null;this.h=new Ii(a);this.j=new Ji(this.h);this.g=null},Li=function(a){Za("__uspapi",function(b){for(var c=[],d=0;d<arguments.length;++d)c[d]=arguments[d];return a.h.h.apply(a.h,Ia(c))})},Mi=function(a){a.g||(a.g=function(b){var c="string"==typeof b.data;try{var d=c?JSON.parse(b.data):b.data}catch(f){return}var e=d.__uspapiCall;e&&"getUSPData"===
e.command&&a.i.__uspapi(e.command,e.version,function(f,g){var h={};h.__uspapiReturn={returnValue:f,success:g,callId:e.callId};f=c?JSON.stringify(h):h;b.source&&"function"===typeof b.source.postMessage&&b.source.postMessage(f,b.origin);return f})},a.i.addEventListener("message",a.g))};
var Ni=function(a){A.call(this,a)};t(Ni,A);var Oi=function(a){A.call(this,a)};t(Oi,A);var Pi=function(a){A.call(this,a)};t(Pi,A);var Qi=function(a){A.call(this,a)};t(Qi,A);var Ri=function(a){A.call(this,a)};t(Ri,A);var Si=function(a){A.call(this,a)};t(Si,A);
var Ti=function(a,b,c,d){this.i=b;this.j=c;this.g="loaded";this.h=this.i&&null==this.j?"hidden":"disabled";this.m=this.i&&this.j?"tcloaded":null;this.o=d;a.__tcfapiEventListeners||(a.__tcfapiEventListeners=[]);this.l=a.__tcfapiEventListeners};
Ti.prototype.s=function(a,b,c,d){if("function"===typeof c)if(b&&2!==b)c(null,!1);else if("error"!==this.g||"ping"===a)switch(a){case "getTCData":if(d&&(!Array.isArray(d)||!d.every(function(e){return"number"===typeof e}))){c(null,!1);break}c(Ui(this,d,null),!0);break;case "ping":c({gdprApplies:this.i,cmpLoaded:!0,cmpStatus:this.g,displayStatus:this.h,apiVersion:"2.0",cmpVersion:1,cmpId:300,gvlVersion:C(this.o,2)||-1,tcfPolicyVersion:C(this.o,3)||-1});break;case "addEventListener":a=this.l.push(c);
c(Ui(this,null,a-1),!0);break;case "removeEventListener":this.l[d]?(this.l[d]=null,c(!0)):c(!1);break;case "getInAppTCData":case "getVendorList":c(null,!1)}};
var Ui=function(a,b,c){if(a.i&&a.j&&"visible"!==a.h){var d=a.j;var e=d.h;var f=qd(e);if(f&&e){var g=I(f,zc,1);f=I(f,rc,2)||new rc;var h=E(g,9,0),k=E(g,4,0),l=E(g,5,0),p=dc(g,10),w=dc(g,11),B=E(g,16,""),u=dc(g,15),T={consents:rd(C(g,13),O),legitimateInterests:rd(C(g,14),O)};b={consents:rd(C(g,17),b),legitimateInterests:rd(C(g,18),b)};var R=rd(C(g,12),Wc),L=ec(g,pc,19);g={};L=r(L);for(var Z=L.next();!Z.done;Z=L.next()){Z=Z.value;var ka=E(Z,1,0);g[ka]=g[ka]||{};for(var Hg=r(C(Z,3)),Rd=Hg.next();!Rd.done;Rd=
Hg.next())g[ka][Rd.value]=E(Z,2,0)}e={tcString:e,tcfPolicyVersion:h,gdprApplies:void 0,cmpId:k,cmpVersion:l,isServiceSpecific:p,useNonStandardStacks:w,publisherCC:B,purposeOneTreatment:u,purpose:T,vendor:b,specialFeatureOptins:R,publisher:{restrictions:g,consents:rd(C(f,1),O),legitimateInterests:rd(C(f,2),O),customPurposes:{consents:rd(C(f,3)),legitimateInterests:rd(C(f,4))}}}}else e=null;e.addtlConsent=d.g;d=e}else d={tcfPolicyVersion:C(a.o,3)||-1,cmpId:300,cmpVersion:1};d.gdprApplies=a.i;d.cmpStatus=
a.g;d.eventStatus=a.m;d.listenerId=c;return d},Vi=function(a){for(var b=0;b<a.l.length;b++){var c=a.l[b];c&&c(Ui(a,null,b),!0)}};
var Wi=function(a){this.g=a};Wi.prototype.setCmpUiShown=function(){var a=this.g;"error"===a.g?a=!1:"visible"===a.h?(a.g="error",a=!1):(a.i=!0,a.g="loaded",a.h="visible",a.m="cmpuishown",Vi(a),a=!0);return a};
Wi.prototype.setUserActionComplete=function(a,b){try{var c=N(Tc,a)}catch(d){return!1}a=od(c);b="1~"+b.join(".");ph();(b=null==a||null==b?null:new qh(a,b))?(a=this.g,"error"===a.g?b=!1:"visible"!==a.h?(a.g="error",b=!1):(a.g="loaded",a.h="hidden",a.m="useractioncomplete",a.j=b,Vi(a),b=!0)):b=!1;return b};Wi.prototype.setError=function(){this.g.g="error"};
var Xi=function(a){this.g=a;this.h=null},Yi=function(a){a.h=function(b){var c="string"==typeof b.data;try{var d=c?JSON.parse(b.data):b.data}catch(f){return}var e=d.__tcfapiCall;!e||"ping"!==e.command&&"getTCData"!==e.command&&"addEventListener"!==e.command&&"removeEventListener"!==e.command||a.g.__tcfapi(e.command,e.version,function(f,g){var h={};h.__tcfapiReturn="removeEventListener"===e.command?{success:f,callId:e.callId}:{returnValue:f,success:g,callId:e.callId};f=c?JSON.stringify(h):h;b.source&&
"function"===typeof b.source.postMessage&&b.source.postMessage(f,b.origin);return f},e.parameter)};a.g.addEventListener("message",a.h);a.g.__tcfapiPostMessageReady=!0};
var Zi=function(a,b,c,d){this.h=a;this.g=new Ti(a,d,b,c);this.i=new Wi(this.g)},$i=function(a){Za("__tcfapi",function(b){for(var c=[],d=0;d<arguments.length;++d)c[d]=arguments[d];return a.g.s.apply(a.g,Ia(c))})};
var aj=function(a){this.g=a;this.h=null};aj.prototype.load=function(){Nh(this.g);bj(this)};
var bj=function(a){a.g.__fcInternalApiPostMessageReady||(a.h=function(b){return cj(a,b)},a.g.addEventListener("message",a.h),a.g.__fcInternalApiPostMessageReady=!0)},cj=function(a,b){var c=b.data.__fciCall;c&&("loaded"!==c.command&&"getM25Consent"!==c.command||"number"!==typeof c.callId||Nh(a.g).push(c.command,function(d){try{var e=N(Hh,d);var f=F(e,1,c.callId)}catch(g){return}d={};d.__fciReturn=M(f);b.source&&"function"===typeof b.source.postMessage&&b.source.postMessage(d,b.origin);return d}))};
var dj=function(a){this.g=a};
var ej=function(a,b){this.g=a;this.h=mb(C(b,4)||"")},fj=function(a){Wg(a.g,a.h,function(){return null},function(){return null})};
var gj=function(a,b,c){this.h=a;this.g=new ci(this.h,b,c)};
var hj=function(a){this.g=a};
var jj=function(a,b){this.g=a;this.m=a.document;this.C=C(b,1);this.A=C(b,4);this.h=b;this.j=rh(this.m);this.v=ph();this.o=ph();this.i=I(b,yh,5);this.s=ij(this);this.B=new hj(this.s);this.l=new ci(this.g,this.A,ij(this));this.D=new dj(this.g)},lj=function(a){Di(a.s).then(function(b){return kj(a,b)},function(){return kj(a,!0)})},kj=function(a,b){var c=I(a.i,gf,2);c=Ug(new Tg(C(c,1),C(c,5),C(c,4),C(c,6),C(c,8),C(c,9),C(c,10),C(c,11)));if(D(a.h,12)){var d=I(a.h,Si,12);d=I(d,Od,1);fj(new ej(a.g,d))}if(D(a.h,
8)){d=(new gj(a.g,a.A,ij(a))).g;var e=sh(d.g);if(e)if(cc(e,7))Sh(d.h,"googlefcInactive");else{ei(d,C(e,3),C(e,4));d=d.j;e=Ef(d.g.document);try{var f=e?N(If,e):null}catch(l){f=null}if((e=f)&&(0<C(e,3).length||0<C(e,4).length)){f=new Eh;if(e){var g=C(e,3);g=G(f,1,g);e=C(e,4);G(g,2,e)}d.h.setM25ConsentObject(M(f));d.i.executeCommandType("getM25Consent")}}}D(a.h,9)&&(g=I(a.h,Pi,9),d=b&&(cc(g,1)||!!a.j),f=I(g,Qi,2),e=1===C(g,3),g=2===C(g,4),!e&&!g&&(e=a.g,g="fc"===e.__tcfapiManager,!e.__tcfapi&&!e.frames.__tcfapiLocator||
g))&&(d=new Zi(e,a.j,f,d),Sh(new Qh,"__tcfapiLocator"),$i(d),Za("__tcfapiManager",d.i),d=d.h,d.__tcfapiPostMessageReady||Yi(new Xi(d)));D(a.h,10)&&(d=Ff(a.m),d=b&&d?C(d,2):null,f=a.g,e="fc"===f.__uspapiManager,!f.__uspapi&&!f.frames.__uspapiLocator||e)&&(d=new Ki(f,d),Sh(new Qh,"__uspapiLocator"),Li(d),Za("__uspapiManager",d.j),Mi(d));if(!(D(a.h,8)&&1===C(I(a.h,Oi,8),1)||di(a.l)||c)){d=a.l;f=sh(d.g)||new If;Sh(d.h,"googlefcInactive");F(f,7,!0);d=d.i;f=M(f);e=!0;e=void 0===e?!1:e;if(g=zf(d.g,"FCCDCF"))try{var h=
N(kf,g)}catch(l){h=new kf}else h=new kf;e=e&&hc(new kf,h)?43200:33696E3;g=new mf;g=F(g,1,f);g=F(g,2,Date.now());K(h,3,g);a:if(f){try{var k=N(If,f)}catch(l){k=!1;break a}k=!!cc(k,7)}else k=!1;k||(K(h,5,void 0),K(h,4,void 0));k=e;k=void 0===k?33696E3:k;f=d.g.location.hostname.split(".");for(tf(d.g,"FCCDCF","");2<=f.length;)tf(d.g,"FCCDCF",f.join(".")),f.shift();hc(new kf,h)?tf(d.g,"FCCDCF",d.h):(h=M(h),(new rf(d.g)).set("FCCDCF",h,{aa:k,path:"/",domain:d.h}),k=(k=zf(d.g,"FCCDCF"))&&k===h?1:2,h=h.length,
f=new zd,f=F(f,3,d.g.location.hostname),h=F(f,2,h),k=F(h,1,k),k=F(k,5,1),d.h&&F(k,4,d.h),h=new yd,k=K(h,1,k),h=new Md,k=fc(h,21,Ld[0],k),ff(d.i,k));tf(d.g,"DATA_USE_CONSENT",d.h)}Sh(new Qh,"googlefcLoaded");a:if(!c){k=Nh(a.g);h=Kh(a.g);(b=!b)||(b=th(),b="suppressConsentMessage"in th()?"boolean"===typeof b.suppressConsentMessage?b.suppressConsentMessage:!1:!1);if(b)b=Bh(1),h.setCmpModeObject(M(b));else{if(D(a.h,8)&&(d=I(a.h,Oi,8),1===C(d,1)||di(a.l))){b=Ch(Bh(2),1);d=1===C(d,2)?2:1;b=F(b,2,d);h.setCmpModeObject(M(b));
k.executeCommandType("loaded");break a}if(D(a.h,9)&&(f=I(a.h,Pi,9),b=1===C(f,3),d=2===C(f,4),f=cc(f,1)||!!a.j,!d&&f)){d=Ch(Bh(3),1);b=F(d,2,b?2:1);h.setCmpModeObject(M(b));k.executeCommandType("loaded");break a}if(D(a.h,10)&&(b=I(a.h,Ri,10),d=Ff(a.m),1===C(b,1)||d&&C(d,2))){b=Ch(Bh(4),2);h.setCmpModeObject(M(b));k.executeCommandType("loaded");break a}b=Bh(1);h.setCmpModeObject(M(b))}k.executeCommandType("loaded")}mj(a);c||nj(a)},nj=function(a){a.g.googletag=a.g.googletag||{cmd:[]};googletag.cmd.push(function(){if(googletag.pubadsReady){var b=
googletag.pubads().getTagSessionCorrelator();if(null!==b){var c=a.B,d=new Hd,e=new xd;b=F(e,1,b);d=K(d,2,b);d=Nd(d);ff(c.g,d)}}})},mj=function(a){var b=$g(),c=new fi(a.i),d=Xg(I(c.g,Od,5)),e=ai(a.g),f=bi(a.g);c=new zi(a.g,c);c.v=b;c.o=a.v;c.m=a.o;c.A=e;c.K=f;Ai(c);b=Bi(c,d);Wg(a.g,b,function(){},function(){var g=a.B;var h=new Hd;var k=new Id;var l=new Jd;var p=new Kd;l=K(l,1,p);k=K(k,1,l);h=K(h,1,k);h=Nd(h);ff(g.g,h)})},ij=function(a){var b={};return new ef(I(a.i,Od,4),(b.pvid=a.v,b.anonid=a.o,b))};
(function(a,b){n[a]=function(c){for(var d=[],e=0;e<arguments.length;++e)d[e]=arguments[e];n[a]=Va;b.apply(null,d)}})("__Y9uNstf385Zx__",function(a,b){b=N(Ni,Wb(b));a=new jj(a,b);b=a.D;var c=I(a.i,xh,10);if(c){var d=b.g.__fcTrace;d=d?N(xh,d):new xh;c=r(ec(c,vh,1));for(var e=c.next();!e.done;e=c.next()){var f=e.value,g=vh;e=ec(d,g,1);f=f?f:new g;g=C(d,1);e.push(f);g.push(J(f))}b.g.__fcTrace=M(d)}b=n.btoa(a.C+"loader_js");d=n.btoa(Date.now().toString());Za(b,d);b=n.btoa(a.C+"cached_js");d=n.btoa(Date.now().toString());
Za(b,d);b=a.g;if(b.frameElement?0:"invoked"!==b.__fcInvoked)a.g.__fcInvoked="invoked",C(a.h,14)&&(a.g.__fcexpdef=C(a.h,14)),(new aj(a.g)).load(),lj(a)});

}catch(e){_._DumpException(e)}
}).call(this,this.default_ContributorServingLoaderClientJs);
// Google Inc.

//# sourceURL=/_/mss/boq-content-ads-contributor/_/js/k=boq-content-ads-contributor.ContributorServingLoaderClientJs.en_US.nIeijzyxCAg.es5.O/d=1/rs=AJlcJMzVjW812mCu4ZY16oyZlrCyH9GbHw/m=loader_js
__Y9uNstf385Zx__(window, 'WyI2YjY2YTI3ZjU0MWVjMTVlIixudWxsLG51bGwsImdlZWtzZm9yZ2Vla3Mub3JnIixbW251bGwsbnVsbCxudWxsLCJodHRwczovL2Z1bmRpbmdjaG9pY2VzbWVzc2FnZXMuZ29vZ2xlLmNvbS9mL0FHU0tXeFhsRmdwZGRXa2hHSGFrZC1iRjFIQzR5OFBCRkRleWpsQVZWcEhRb2piTHJrU0FOMGRFT1VraHpUOFFUZm1PbHlJZVh2akxwaXNVelRlX1ZpekVERG9cdTAwM2QiXSxbIkNVSUQiLG51bGwsbnVsbCwiQVFBQiIsInhqRCszbi8yZGc5ZjVVRkFJVWYrNHZoWkdRU2MzRUtoZGV0d2EyN2RWMExMYjdaYXo3d0JGL1NYZ3ROTDgwZmp0eXMrcGpnYTVjWitoVGd4aURIYkprNllzWGR2bjNSRmpDMG5vdXhoeitpbCtxbEJwSUdKRVRuYUN4RnRkUXFaNndWdHVlUTY0a1k3QkNMWGRwazdmYkhmd1dhMmdPYWZFNGNWZ241WHR6RW5taUxITFFITSs3VFUvaXJCeExwK0trQ1JKbFJXa3RzT1VzZWxmdGxkYVRvNDNRZzhGTlpxUFluMlpTL1oyMS8xZER1OEloNUdTQ01JVUw1M2dyUlhDS2JxaDhvU3VqSmJDVGNCUVgxb1dRVzd5ZC9GU1R0OWZEOEdIODVMVWxraHR3WEJkcXJka2cyb1RWRHF4alhHd1pzZjZBZkxiM0k0Mk92WVlqSkhtUVx1MDAzZFx1MDAzZCIsIjZiNjZhMjdmNTQxZWMxNWUiLCJyZWZjb24iLDkwMDAwMCw2MDAwMCw2MDAwMCw4NjQwMDAwMCwiUCwxNjI4NjE1MTExOTE0OkFMSEdMdVFBQUFBUFVDd3hOakk0TmpFMU1URXhPVEUwSjA3anFjT0tqd2thMEt0aGtEY1JGQVFUNDRVdkwwWTdYK3RXZ2w4blkxNTZBSlQyaTRuRmFRcm5hYzljTWpPOEhRemJWMDhoVFNnbG5FMmthTTZIeE41M2daUkNaSEsrRzJOVGNQVlVTLzNCdkdXc2dvNm9JL0ZJUlE5NTJvSzcrdWQzeWhoWCt2aHFseVJmNGdTQW5vcWFOZGFqV1MrN2JmSTN4VFdlR2xLYlRWamRKRnNQTUI1MTZXLzZyaWVJekxtYWFLSVEzTVc2ZmlZbUhHdmd2MTk1Y1U2ZTBaNmkyaXpRUUtNUTVOTlQyeW9OZkkzRWNvS0VpWjVoektNem9NUE9Qc1JwZHNBYUlPRTc4S3A0dXBlRTBIQjRNSWxpMTZRNENkUnVLZFFKNVk3MUlzZTVDMWFHaTZ1UFBlRVNIK3JOV2FCNjNUZjVqQU9PaE9QYldnXHUwMDNkXHUwMDNkIiwyNTkyMDAwXSxbbnVsbCxudWxsLCJodHRwczovL3N1cHBvcnQuZ29vZ2xlLmNvbS9jb250cmlidXRvci9hbnN3ZXIvNzY4Nzk4NSJdLFtudWxsLG51bGwsbnVsbCwiaHR0cHM6Ly9mdW5kaW5nY2hvaWNlc21lc3NhZ2VzLmdvb2dsZS5jb20vZWwvQUdTS1d4VjRUTzB6TjJVT2VTOEdTaWJEejdXNklZTkFKTGRsaXhVMzV6eDJjVmhDa2ttRkhBd05IRExnNmNYRVZXVnJETUxYeUhaUFExUzB0Zlh1TkJnMV9CTVx1MDAzZCJdLFtudWxsLG51bGwsbnVsbCwiaHR0cHM6Ly9mdW5kaW5nY2hvaWNlc21lc3NhZ2VzLmdvb2dsZS5jb20vZi9BR1NLV3hVbUlKellUeDhzQkM3cHEydU5mYjJCMXpXZmVPekRVbDV3dEN0LW1hc3haUXFQTHk1clo1VWpFR0pTU3ctRC01Rko2YzBYZGlzWHJPdWx0MW03ZjFRXHUwMDNkIl0sbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsIjZiNjZhMjdmNTQxZWMxNWUiXSxudWxsLG51bGwsbnVsbCxbMSxbMiwxMDIsMl0sMiwxXSxudWxsLG51bGwsbnVsbCxudWxsLCJbXCJ4JTcyOzE2NDUwIVx1MDAzZGVmZHdhKic3NjQ2NDEyXHUwMDNkJD93cXJmKyowMTUwNzI2MiUyYmVqdmZcXC8lNzI7MTI\/XHUwMDNkOiFcdTAwM2RlZmR3YSonNzY0NjBcXHUwMDNDXFx1MDAzQzIkP2Via3BidVwiXSJd');