addAndMultiply:
	scalac addAndMultiply.scala

listMultiplier:
	scalac listMultiplier.scala

listMultiplierReuse:
	scalac listMultiplierReuse.scala

lambdaAsParameter:
	scalac lambdaAsParameter.scala

all: addAndMultiply listMultiplier listMultiplierReuse lambdaAsParameter

clean:
	rm -rf *.class
